# Generated by Django 5.2.17 on 2026-09-09 05:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('organizations', '0013_seed_milestone11_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase (+ IN)'), ('decrease', 'Decrease (- OUT)')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('reason_category', models.CharField(choices=[('calibration_adjustment', 'Calibration Adjustment'), ('spillage_or_leakage', 'Spillage or Leakage'), ('temperature_variation', 'Temperature Variation'), ('handling_loss', 'Handling / Evaporation Loss'), ('system_correction', 'System Correction'), ('other', 'Other Reason')], max_length=50)),
                ('explanation', models.TextField()),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorised_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='organizations.outlet')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='forecourt.tank')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='stock_adjustments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.stockadjustment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_stock_adjustment_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TankStockBalanceProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_book_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('has_chronology_conflict', models.BooleanField(default=False)),
                ('has_negative_balance_history', models.BooleanField(default=False)),
                ('first_negative_balance_at', models.DateTimeField(blank=True, null=True)),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_projections', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_projections', to='organizations.outlet')),
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_projection', to='forecourt.tank')),
            ],
            options={
                'ordering': ['tank__code'],
            },
        ),
        migrations.CreateModel(
            name='TankStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code_snapshot', models.CharField(max_length=50)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('movement_type', models.CharField(choices=[('initial_opening_balance', 'Initial Opening Balance'), ('tanker_receipt', 'Tanker Receipt'), ('nozzle_dispensing', 'Nozzle Gross Dispensing'), ('testing_return', 'Testing Fuel Returned'), ('stock_adjustment_increase', 'Stock Adjustment (Increase)'), ('stock_adjustment_decrease', 'Stock Adjustment (Decrease)'), ('reversal', 'Ledger Reversal')], max_length=40)),
                ('direction', models.CharField(choices=[('IN', 'Inward (Receipt/Return/Increase)'), ('OUT', 'Outward (Dispensing/Decrease)')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('effective_at', models.DateTimeField(db_index=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.UUIDField(db_index=True)),
                ('source_line_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('fuel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='forecourt.fuelproduct')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_stock_movements', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_stock_movements', to='organizations.outlet')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.tankstockmovement')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='forecourt.tank')),
            ],
            options={
                'ordering': ['effective_at', 'created_at', 'id'],
                'indexes': [models.Index(fields=['tank', 'effective_at', 'created_at'], name='inventory_t_tank_id_50658b_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_t_source__792461_idx')],
            },
        ),
    ]
