# Generated by Django 5.2.17 on 2026-09-09 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('inventory', '0002_backfill_existing_stock_data'),
        ('organizations', '0013_seed_milestone11_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tankstockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_line_id__isnull', False)), fields=('source_type', 'source_id', 'source_line_id', 'movement_type', 'tank'), name='unique_stock_movement_source_line_tank'),
        ),
        migrations.AddConstraint(
            model_name='tankstockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_line_id__isnull', True)), fields=('source_type', 'source_id', 'movement_type', 'tank'), name='unique_stock_movement_source_tank'),
        ),
    ]
