# Generated by Django 5.2.17 on 2026-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_tankstockmovement_unique_stock_movement_source_line_tank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tankstockmovement',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
