# Generated by Django 5.2.17 on 2026-09-11 08:31

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment_business_date_and_more'),
        ('organizations', '0017_seed_purchase_tax_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(choices=[('fuel', 'Fuel'), ('stock_item', 'Stock Item'), ('non_stock_item', 'Non-stock Item'), ('service', 'Service')], default='stock_item', max_length=30)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('inventory_tracking_mode', models.CharField(choices=[('tank', 'Tank Ledger'), ('quantity', 'Quantity Ledger'), ('none', 'No Inventory Tracking')], default='quantity', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organizations.organisation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tankstockmovement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.item'),
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organizations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='organizations.organisation')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='inventory.unitmaster')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='inventory.unitmaster')),
            ],
            options={
                'ordering': ['from_unit__name', 'to_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='StockItemProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('weighted_average', 'Weighted Average')], default='fifo', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_profile', to='inventory.item')),
                ('preferred_purchase_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_purchase_stock_profiles', to='inventory.unitmaster')),
                ('sales_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_stock_profiles', to='inventory.unitmaster')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unitmaster'),
        ),
        migrations.CreateModel(
            name='FuelItemProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel_category', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('premium_petrol', 'Premium Petrol'), ('premium_diesel', 'Premium Diesel'), ('cng', 'CNG'), ('adblue', 'AdBlue'), ('other', 'Other')], default='petrol', max_length=50)),
                ('custom_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_code', models.CharField(blank=True, max_length=50, null=True)),
                ('density_std', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('density_min', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('density_max', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('price_configuration_eligible', models.BooleanField(default=True)),
                ('forecourt_display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_profile', to='inventory.item')),
                ('stock_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_profiles', to='inventory.unitmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCodeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_code', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('is_conflict', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_code_aliases', to='organizations.organisation')),
            ],
            options={
                'ordering': ['alias_code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('alias_code'), models.F('organisation'), name='unique_org_item_alias_code_ci')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitmaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_unit_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='unitmaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organisation'), name='unique_org_unit_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('organisation', 'item', 'from_unit', 'to_unit'), name='unique_org_item_unit_conversion'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_item_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('organisation', 'barcode'), name='unique_org_item_barcode'),
        ),
    ]
