# Generated by Django 5.2.17 on 2026-09-15 04:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_backfill_canonical_items'),
        ('organizations', '0019_seed_supplier_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_date', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('IN', 'Inward'), ('OUT', 'Outward')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock_adjustments', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock_adjustments', to='organizations.outlet')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_item_stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-adjustment_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_stock_adjustment_qty_positive')],
            },
        ),
        migrations.CreateModel(
            name='ItemStockBalanceProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('last_movement_date', models.DateField(blank=True, null=True)),
                ('has_negative_balance_history', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_projections', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stock_projections', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stock_projections', to='organizations.outlet')),
            ],
            options={
                'ordering': ['item__name'],
                'constraints': [models.UniqueConstraint(fields=('outlet', 'item'), name='unique_outlet_item_stock_projection')],
            },
        ),
        migrations.CreateModel(
            name='ItemStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code_snapshot', models.CharField(max_length=50)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('unit_code_snapshot', models.CharField(max_length=20)),
                ('movement_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('adjustment_in', 'Stock Adjustment In'), ('adjustment_out', 'Stock Adjustment Out'), ('sales_invoice', 'Sales Invoice'), ('reversal', 'Reversal')], max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'Inward'), ('OUT', 'Outward')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('effective_date', models.DateField(db_index=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.UUIDField(db_index=True)),
                ('source_line_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_item_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_movements', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock_movements', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_stock_movements', to='organizations.outlet')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.itemstockmovement')),
            ],
            options={
                'ordering': ['effective_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['outlet', 'item', 'effective_date'], name='inventory_i_outlet__4b9c6c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='item_stock_movement_qty_positive')],
            },
        ),
    ]
