# Generated by Django 5.2.17 on 2026-09-09 05:25

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('operations', '0002_nozzlecommissioning_nozzlecommissioningauditlog_and_more'),
        ('organizations', '0013_seed_milestone11_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TankerReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=100)),
                ('supplier_name_snapshot', models.CharField(max_length=255)),
                ('supplier_code_snapshot', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('delivery_challan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_registration', models.CharField(max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('seal_details', models.TextField(blank=True, null=True)),
                ('unloading_start_time', models.DateTimeField(blank=True, null=True)),
                ('unloading_end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('confirmed', 'Confirmed'), ('voided', 'Voided')], default='recorded', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tanker_receipts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tanker_receipts', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanker_receipts', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanker_receipts', to='organizations.outlet')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanker_receipts', to='purchases.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tanker_receipts', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_tanker_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unloading_end_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TankerReceiptAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='tanker_receipts/%Y/%m/')),
                ('attachment_type', models.CharField(choices=[('invoice', 'Invoice Document'), ('challan', 'Delivery Challan'), ('dip_sheet', 'Dip / Calibration Sheet'), ('receipt_image', 'Tanker / Meter Photo'), ('other', 'Other Attachment')], default='invoice', max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchases.tankerreceipt')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipt_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TankerReceiptProductLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('accepted_book_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('invoice_density', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('observed_density', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('observed_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity_override_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='forecourt.fuelproduct')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='purchases.tankerreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='TankerReceiptTankAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_book_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('pre_unloading_dip_height', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pre_unloading_dip_unit', models.CharField(choices=[('millimetre', 'Millimetre (mm)'), ('centimetre', 'Centimetre (cm)'), ('inch', 'Inch (in)')], default='millimetre', max_length=20)),
                ('pre_unloading_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('post_unloading_dip_height', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('post_unloading_dip_unit', models.CharField(choices=[('millimetre', 'Millimetre (mm)'), ('centimetre', 'Centimetre (cm)'), ('inch', 'Inch (in)')], default='millimetre', max_length=20)),
                ('post_unloading_volume', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('physical_dip_gain', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('conversion_method', models.CharField(blank=True, max_length=50, null=True)),
                ('variance_status', models.CharField(choices=[('normal', 'Normal'), ('shortage', 'Shortage'), ('excess', 'Excess'), ('acknowledged', 'Acknowledged')], default='normal', max_length=30)),
                ('variance_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('variance_acknowledgement_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('calibration_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_allocations', to='operations.dipcalibrationchart')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchases.tankerreceiptproductline')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='forecourt.tank')),
                ('variance_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_receipt_variances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_supplier_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organisation'), name='unique_org_supplier_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='tankerreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('outlet', 'receipt_number'), name='unique_active_outlet_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='tankerreceiptproductline',
            constraint=models.UniqueConstraint(fields=('receipt', 'product'), name='unique_receipt_product_line'),
        ),
        migrations.AddConstraint(
            model_name='tankerreceipttankallocation',
            constraint=models.UniqueConstraint(fields=('product_line', 'tank'), name='unique_receipt_line_tank_allocation'),
        ),
    ]
