# Generated by Django 5.2.17 on 2026-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankerreceipt',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
