# Generated by Django 5.2.17 on 2026-09-10 05:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('organizations', '0014_outlet_timezone'),
        ('purchases', '0002_tankerreceipt_business_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name_snapshot', models.CharField(max_length=255)),
                ('supplier_code_snapshot', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=100)),
                ('supplier_invoice_number', models.CharField(max_length=100)),
                ('normalized_supplier_invoice_number', models.CharField(db_index=True, max_length=100)),
                ('is_duplicate_override', models.BooleanField(default=False)),
                ('duplicate_override_reason', models.TextField(blank=True, null=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('additional_charges_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('round_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('conflicting_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overriding_bills', to='purchases.purchasebill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bills', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bills', to='organizations.outlet')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='purchases.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_purchase_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillAdjustmentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('charge', 'Charge'), ('discount', 'Discount'), ('tax', 'Tax'), ('round_off', 'Round Off')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed_amount', max_length=20)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='purchases.purchasebill')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='purchase_bills/%Y/%m/')),
                ('attachment_type', models.CharField(choices=[('supplier_invoice', 'Supplier Invoice'), ('delivery_challan', 'Delivery Challan'), ('tax_document', 'Tax Document'), ('note_reference', 'Debit/Credit Note Reference'), ('other', 'Other Supporting Document')], default='supplier_invoice', max_length=40)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='purchases.purchasebill')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bill_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_totals', models.JSONField(blank=True, default=dict)),
                ('new_totals', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_audits', to=settings.AUTH_USER_MODEL)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='purchases.purchasebill')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillReceiptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linked_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('linked_invoice_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bill_receipt_links', to=settings.AUTH_USER_MODEL)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_links', to='purchases.purchasebill')),
                ('receipt_product_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='purchases.tankerreceiptproductline')),
                ('tanker_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='purchases.tankerreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('line_type', models.CharField(choices=[('fuel', 'Fuel'), ('other', 'Other Item')], default='fuel', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('unit', models.CharField(default='Litre', max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('quantity_override_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='forecourt.fuelproduct')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.purchasebill')),
                ('receipt_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='purchases.purchasebillreceiptlink')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bill_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('is_duplicate_override', False), ('status', 'active')), fields=('organisation', 'supplier', 'normalized_supplier_invoice_number'), name='unique_active_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'voided'), _negated=True), fields=('outlet', 'bill_number'), name='unique_active_outlet_bill_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasebillreceiptlink',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True), ('receipt_product_line__isnull', False)), fields=('receipt_product_line',), name='unique_active_receipt_product_line_link'),
        ),
        migrations.AddConstraint(
            model_name='purchasebillsequence',
            constraint=models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_bill_seq_year'),
        ),
    ]
