# Generated by Django 5.2.17 on 2026-09-10 08:06

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('organizations', '0017_seed_purchase_tax_permissions'),
        ('purchases', '0004_staged_legacy_v1_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='cgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='discount_mode',
            field=models.CharField(choices=[('line_level', 'Line Level Discounts'), ('transaction_level', 'Transaction Level Discount')], default='line_level', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gst_cess_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='igst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_overseas_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_place_of_supply_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='other_charges_subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='other_charges_tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='outlet_gstin_snapshot',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='outlet_state_code_snapshot',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='outlet_state_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='petroleum_tax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='place_of_supply_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='place_of_supply_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='place_of_supply_state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_type',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('goods_services', 'Goods & Services'), ('mixed', 'Mixed (Fuel & Goods/Services)')], default='fuel', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='sgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier_gstin_snapshot',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier_state_code_snapshot',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier_state_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tax_price_mode',
            field=models.CharField(choices=[('tax_exclusive', 'Tax Exclusive'), ('tax_inclusive', 'Tax Inclusive')], default='tax_exclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='taxable_value_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='transaction_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='transaction_discount_method',
            field=models.CharField(choices=[('none', 'None'), ('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='transaction_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='allocated_transaction_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='cess_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='discount_method',
            field=models.CharField(choices=[('none', 'None'), ('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='is_petroleum_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='petroleum_manual_override_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='petroleum_tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_code_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_components_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_treatment',
            field=models.CharField(default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='calculation_version',
            field=models.CharField(choices=[('legacy_v1', 'Legacy V1'), ('item_tax_v2', 'Item Tax V2')], db_index=True, default='item_tax_v2', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20)),
                ('unit', models.CharField(default='NOS', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_tax_treatment', models.CharField(choices=[('gst', 'GST Taxable'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('out_of_scope', 'Out of Scope'), ('non_gst_petroleum', 'Non-GST Petroleum')], default='gst', max_length=30)),
                ('default_itc_classification', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_review', 'Pending Review'), ('eligible_inputs', 'Eligible - Inputs'), ('eligible_capital_goods', 'Eligible - Capital Goods'), ('eligible_input_services', 'Eligible - Input Services'), ('ineligible_blocked', 'Ineligible - Blocked Credit'), ('ineligible_other', 'Ineligible - Others')], default='pending_review', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='organizations.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='purchases.purchaseitem'),
        ),
        migrations.CreateModel(
            name='PurchaseTaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('tax_regime', models.CharField(choices=[('gst', 'GST'), ('non_gst_petroleum', 'Non-GST Petroleum'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('out_of_scope', 'Out of Scope')], default='gst', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_codes', to='organizations.organisation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='default_purchase_tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaulted_purchase_items', to='purchases.purchasetaxcode'),
        ),
        migrations.CreateModel(
            name='ProductPurchaseTaxMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_tax_treatment', models.CharField(default='non_gst_petroleum', max_length=30)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('default_itc_classification', models.CharField(default='not_applicable', max_length=30)),
                ('purchase_unit', models.CharField(default='Litre', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_mapping', to='forecourt.fuelproduct')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_mappings', to='organizations.organisation')),
                ('purchase_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_mapping', to='purchases.purchaseitem')),
                ('purchase_tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_mappings', to='purchases.purchasetaxcode')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='purchases.purchasetaxcode'),
        ),
        migrations.CreateModel(
            name='PurchaseTaxCodeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cess_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='purchases.purchasetaxcode')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTaxCodeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('vat', 'State VAT / Local Sales Tax'), ('additional_tax', 'Additional Tax'), ('cess', 'Cess / Surcharge'), ('excise', 'Excise Component'), ('other_levy', 'Other Petroleum Levy')], default='vat', max_length=30)),
                ('calculation_base', models.CharField(choices=[('discounted_line_value', 'Discounted Line Value'), ('taxable_value', 'Taxable Value'), ('value_plus_previous_components', 'Value Plus Previous Components'), ('quantity', 'Quantity (Per Unit)'), ('manual_invoice_amount', 'Manual Invoice Amount')], default='discounted_line_value', max_length=40)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Percentage'), ('per_unit', 'Per Unit Rate'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('rate_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('rate_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='purchases.purchasetaxcoderate')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillOtherCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('freight', 'Freight / Transportation'), ('insurance', 'Insurance'), ('packing_handling', 'Packing & Handling'), ('other', 'Other Charges')], default='freight', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('calculation_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed_amount', max_length=20)),
                ('percentage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_treatment', models.CharField(choices=[('taxable', 'Taxable'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('non_gst', 'Non-GST')], default='taxable', max_length=20)),
                ('hsn_sac', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_charges', to='purchases.purchasebill')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_charges', to='purchases.purchasetaxcode')),
                ('tax_code_rate_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_charges', to='purchases.purchasetaxcoderate')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_code_rate_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='purchases.purchasetaxcoderate'),
        ),
        migrations.AddConstraint(
            model_name='purchasetaxcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_purchase_tax_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_purchase_item_code_ci'),
        ),
    ]
