# Generated by Django 5.2.17 on 2026-09-11 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_tankstockmovement_item_unitmaster_and_more'),
        ('organizations', '0017_seed_purchase_tax_permissions'),
        ('purchases', '0005_unified_taxation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchasetaxmapping',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_mapping', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='effective_rate_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bill_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_regime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_treatment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillline',
            name='tax_treatment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='canonical_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_purchase_item', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchasetaxcode',
            name='is_purchase_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchasetaxcode',
            name='is_sales_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tankerreceiptproductline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tanker_receipt_lines', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='discount_mode',
            field=models.CharField(choices=[('line', 'Line Level Discounts'), ('transaction', 'Transaction Level Discount'), ('line_level', 'Line Level Discounts'), ('transaction_level', 'Transaction Level Discount')], default='line', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='tax_price_mode',
            field=models.CharField(choices=[('exclusive', 'Tax Exclusive'), ('inclusive', 'Tax Inclusive'), ('tax_exclusive', 'Tax Exclusive'), ('tax_inclusive', 'Tax Inclusive')], default='exclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasetaxcode',
            name='tax_regime',
            field=models.CharField(choices=[('gst', 'GST'), ('non_gst_petroleum', 'Non-GST Petroleum'), ('non_gst', 'Non-GST'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('out_of_scope', 'Out of Scope')], default='gst', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemPurchaseTaxTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_itc_classification', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending_review', 'Pending Review'), ('eligible_inputs', 'Eligible - Inputs'), ('eligible_capital_goods', 'Eligible - Capital Goods'), ('eligible_input_services', 'Eligible - Input Services'), ('ineligible_blocked', 'Ineligible - Blocked Credit'), ('ineligible_other', 'Ineligible - Others')], default='pending_review', max_length=30)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax_treatments', to='inventory.item')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_tax_treatments', to='organizations.organisation')),
                ('tax_treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapped_items', to='purchases.purchasetaxcode')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
