# Generated by Django 5.2.17 on 2026-09-15 09:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0020_seed_sales_and_item_stock_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('allow_manual_posting', models.BooleanField(default=True)),
                ('system_key', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_accounts', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='organizations.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_number', models.CharField(max_length=100)),
                ('entry_date', models.DateField(db_index=True)),
                ('source_type', models.CharField(default='manual_journal', max_length=50)),
                ('source_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('narration', models.TextField()),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=20)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.outlet')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('account_code_snapshot', models.CharField(max_length=30)),
                ('account_name_snapshot', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('party_type', models.CharField(blank=True, max_length=30)),
                ('party_id', models.UUIDField(blank=True, null=True)),
                ('party_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='JournalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriodLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the locked accounting month.')),
                ('reason', models.TextField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.TextField(blank=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_accounting_periods', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_period_locks', to='organizations.organisation')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_period_locks', to='organizations.outlet')),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_accounting_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('outlet__isnull', False), ('unlocked_at__isnull', True)), fields=('organisation', 'outlet', 'month'), name='unique_active_outlet_period_lock'), models.UniqueConstraint(condition=models.Q(('outlet__isnull', True), ('unlocked_at__isnull', True)), fields=('organisation', 'month'), name='unique_active_org_period_lock')],
            },
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_ledger_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('organisation', 'system_key'), name='unique_org_ledger_system_key'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('outlet', 'journal_number'), name='unique_outlet_journal_number'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('organisation', 'outlet', 'client_request_id'), name='unique_journal_client_request'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), models.Q(('source_type', 'journal_reversal'), _negated=True)), fields=('organisation', 'outlet', 'source_type', 'source_id'), name='unique_journal_source'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_debit__gt', 0)), name='journal_total_debit_positive'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_credit__gt', 0)), name='journal_total_credit_positive'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(fields=('journal', 'sequence'), name='unique_journal_line_sequence'),
        ),
        migrations.AddConstraint(
            model_name='journalsequence',
            constraint=models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_journal_sequence'),
        ),
    ]
