# Generated by Django 5.2.17 on 2026-09-16 09:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_seed_settlement_accounts'),
        ('finance', '0011_digitalsettlement_accounting_basis_and_more'),
        ('organizations', '0022_seed_digital_settlement_permissions'),
        ('shifts', '0012_fuelcreditslip_is_credit_limit_overridden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAccountingPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('fuel_sales_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('card_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('upi_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fleet_card_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_slip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approved_increase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approved_decrease_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('shortage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('excess_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reversed', 'Reversed')], default='active', max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_accounting_postings', to='finance.paymentaccount')),
                ('operational_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_postings', to='shifts.operationalshift')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_accounting_postings', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_accounting_postings', to='organizations.outlet')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_shift_accounting', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_shift_accounting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['operational_shift', 'version'],
                'constraints': [models.UniqueConstraint(fields=('operational_shift', 'version'), name='unique_shift_accounting_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('operational_shift',), name='unique_active_shift_accounting'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='shift_accounting_version_positive')],
            },
        ),
    ]
