# Generated by Django 5.2.17 on 2026-08-26 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('organizations', '0005_seed_forecourt_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DipCalibrationChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('nominal_capacity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tank_diameter', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('tank_length', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('manufacturer_or_source', models.CharField(blank=True, max_length=255, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='calibration_charts/')),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('original_height_unit', models.CharField(choices=[('millimetre', 'Millimetre (mm)'), ('centimetre', 'Centimetre (cm)'), ('inch', 'Inch (in)')], default='millimetre', max_length=30)),
                ('normalized_height_unit', models.CharField(default='millimetre', max_length=30)),
                ('volume_unit', models.CharField(default='litre', max_length=30)),
                ('lookup_mode', models.CharField(choices=[('exact_only', 'Exact Match Only'), ('linear_interpolation', 'Linear Interpolation')], default='linear_interpolation', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_charts', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_charts', to='organizations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('confirmed', 'Confirmed')], default='preparing', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_opening_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opening_batches', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_batches', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance_batches', to='organizations.outlet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TankCalibrationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tank_charts', to=settings.AUTH_USER_MODEL)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_assignments', to='operations.dipcalibrationchart')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_calibration_assignments', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_calibration_assignments', to='organizations.outlet')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_assignments', to='forecourt.tank')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='DipCalibrationPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height_mm', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume_litres', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sequence', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='operations.dipcalibrationchart')),
            ],
            options={
                'ordering': ['sequence', 'height_mm'],
                'constraints': [models.UniqueConstraint(fields=('chart', 'height_mm'), name='unique_chart_height_mm')],
            },
        ),
        migrations.CreateModel(
            name='NozzleOpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalizer_reading', models.DecimalField(decimal_places=3, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='forecourt.nozzle')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_balances', to='operations.openingbalancebatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'nozzle'), name='unique_batch_nozzle_opening_balance')],
            },
        ),
        migrations.CreateModel(
            name='TankOpeningBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('physical_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('raw_dip_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('raw_dip_unit', models.CharField(blank=True, choices=[('millimetre', 'Millimetre (mm)'), ('centimetre', 'Centimetre (cm)'), ('inch', 'Inch (in)')], max_length=30, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('conversion_method', models.CharField(choices=[('calibration_exact', 'Calibration Exact Match'), ('calibration_interpolated', 'Calibration Interpolation'), ('manual_quantity', 'Manual Quantity Entry')], default='manual_quantity', max_length=50)),
                ('manual_quantity_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_balances', to='operations.openingbalancebatch')),
                ('calibration_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances', to='operations.tankcalibrationassignment')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='forecourt.tank')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'tank'), name='unique_batch_tank_opening_balance')],
            },
        ),
    ]
