# Generated by Django 5.2.17 on 2026-09-04 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('operations', '0001_initial'),
        ('organizations', '0008_seed_handover_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NozzleCommissioning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_at', models.DateTimeField()),
                ('initial_totalizer', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispenser_code_snapshot', models.CharField(max_length=50)),
                ('nozzle_code_snapshot', models.CharField(max_length=50)),
                ('product_id_snapshot', models.UUIDField()),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('commissioned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissioned_nozzles', to=settings.AUTH_USER_MODEL)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissionings', to='forecourt.nozzle')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_commissionings', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_commissionings', to='organizations.outlet')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NozzleCommissioningAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='nozzle_commissioned', max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzle_commissioning_audits', to=settings.AUTH_USER_MODEL)),
                ('commissioning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='operations.nozzlecommissioning')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissioning_audit_logs', to='forecourt.nozzle')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_commissioning_audit_logs', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_commissioning_audit_logs', to='organizations.outlet')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nozzlecommissioning',
            constraint=models.UniqueConstraint(fields=('nozzle',), name='unique_nozzle_commissioning'),
        ),
    ]
