# Generated by Django 5.2.17 on 2026-08-26 06:34

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('organizations', '0005_seed_forecourt_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='organizations.outlet')),
            ],
            options={
                'ordering': ['display_order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('is_locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rosters', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='organizations.outlet')),
                ('shift_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='shifts.shiftdefinition')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', 'shift_definition__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ShiftStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_cashier', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty_designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='employees.employeedesignation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='employees.employee')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='shifts.shiftroster')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftNozzleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='forecourt.nozzle')),
                ('staff_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_assignments', to='shifts.shiftstaffassignment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shiftdefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('outlet'), name='unique_outlet_shift_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='shiftdefinition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('outlet'), name='unique_outlet_shift_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='shiftroster',
            constraint=models.UniqueConstraint(fields=('outlet', 'shift_definition', 'business_date'), name='unique_outlet_shift_business_date_roster'),
        ),
        migrations.AddConstraint(
            model_name='shiftstaffassignment',
            constraint=models.UniqueConstraint(fields=('roster', 'employee'), name='unique_roster_employee_assignment'),
        ),
    ]
