# Generated by Django 5.2.17 on 2026-09-02 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('shifts', '0002_operationalshift_operationalshiftstaff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalShiftCashierPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='operationalshiftnozzleassignment',
            options={'ordering': ['effective_from']},
        ),
        migrations.RemoveConstraint(
            model_name='operationalshiftnozzleassignment',
            name='unique_shift_nozzle_assignment',
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='assignment_type',
            field=models.CharField(choices=[('shift_start', 'Shift Start'), ('handover', 'Handover Transfer'), ('midshift_activation', 'Mid-shift Activation'), ('correction', 'Assignment Correction')], default='shift_start', max_length=50),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='closing_reading',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_nozzle_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='opening_reading',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='operationalshiftnozzleassignment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshiftstaff',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_shift_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalshiftstaff',
            name='duty_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_shift_assignments', to='employees.employeedesignation'),
        ),
        migrations.AddField(
            model_name='operationalshiftstaff',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operationalshiftstaff',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='operationalshiftnozzleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('shift', 'nozzle'), name='unique_active_shift_nozzle_assignment'),
        ),
        migrations.AddField(
            model_name='operationalshiftcashierperiod',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashier_period_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalshiftcashierperiod',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_periods', to='shifts.operationalshift'),
        ),
        migrations.AddField(
            model_name='operationalshiftcashierperiod',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_periods', to='shifts.operationalshiftstaff'),
        ),
        migrations.AddConstraint(
            model_name='operationalshiftcashierperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('shift',), name='unique_active_shift_cashier_period'),
        ),
    ]
