# Generated by Django on 2026-09-02

from django.db import migrations

def backfill_operational_assignments(apps, schema_editor):
    OperationalShift = apps.get_model('shifts', 'OperationalShift')
    OperationalShiftStaff = apps.get_model('shifts', 'OperationalShiftStaff')
    OperationalShiftNozzleAssignment = apps.get_model('shifts', 'OperationalShiftNozzleAssignment')
    OperationalShiftCashierPeriod = apps.get_model('shifts', 'OperationalShiftCashierPeriod')
    ShiftNozzleMeter = apps.get_model('shifts', 'ShiftNozzleMeter')

    # Backfill OperationalShiftStaff and Cashier Periods
    for staff in OperationalShiftStaff.objects.select_related('shift').all():
        shift = staff.shift
        staff.effective_from = shift.opened_at
        if shift.status == 'closed' and shift.closed_at:
            staff.effective_to = shift.closed_at
        staff.added_by = shift.opened_by
        staff.save(update_fields=['effective_from', 'effective_to', 'added_by'])

        # Create cashier period for primary cashiers if one doesn't exist
        if staff.is_primary_cashier:
            OperationalShiftCashierPeriod.objects.get_or_create(
                shift=shift,
                staff=staff,
                defaults={
                    'effective_from': shift.opened_at,
                    'effective_to': shift.closed_at if (shift.status == 'closed' and shift.closed_at) else None,
                    'changed_by': shift.opened_by,
                    'reason': 'Shift initial primary cashier'
                }
            )

    # Backfill OperationalShiftNozzleAssignment
    for na in OperationalShiftNozzleAssignment.objects.select_related('shift').all():
        shift = na.shift
        na.effective_from = shift.opened_at
        if shift.status == 'closed' and shift.closed_at:
            na.effective_to = shift.closed_at
        na.assignment_type = 'shift_start'
        na.created_by = shift.opened_by

        # Link readings from corresponding ShiftNozzleMeter
        meter = ShiftNozzleMeter.objects.filter(shift=shift, nozzle=na.nozzle).first()
        if meter:
            na.opening_reading = meter.opening_reading
            if shift.status == 'closed' and meter.closing_reading is not None:
                na.closing_reading = meter.closing_reading

        na.save(update_fields=['effective_from', 'effective_to', 'assignment_type', 'created_by', 'opening_reading', 'closing_reading'])


def rollback_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_operationalshiftcashierperiod_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_operational_assignments, rollback_backfill),
    ]
