# Generated by Django 5.2.17 on 2026-09-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_backfill_assignment_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftnozzlemeter',
            name='manual_exception_type',
            field=models.CharField(blank=True, choices=[('first_time_setup_exception', 'First-time setup exception'), ('new_or_replaced_meter', 'New or replaced meter'), ('meter_reset', 'Meter reset'), ('totalizer_rollover', 'Totalizer rollover'), ('approved_correction', 'Approved correction'), ('midshift_activation', 'Mid-shift nozzle activation')], max_length=50, null=True),
        ),
    ]
