# Generated by Django 5.2.17 on 2026-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shiftnozzlemeter_manual_exception_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftnozzlemeter',
            name='opening_source',
            field=models.CharField(choices=[('previous_shift', 'Previous Shift'), ('commissioning', 'Nozzle Commissioning'), ('opening_balance', 'Opening Balance'), ('manual_exception', 'Manual Exception')], default='previous_shift', max_length=30),
        ),
    ]
