# Generated by Django 5.2.17 on 2026-09-07 11:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0011_seed_milestone10_permissions'),
        ('shifts', '0008_customer_collectionauditlog_customeroutletassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshiftsettlement',
            name='fleet_card_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='employeeshiftsettlement',
            name='shortage_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeshiftsettlement',
            name='shortage_acknowledged_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='actual_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='actual_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='lock_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalshift',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='conflict_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='conflict_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_meter_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='continuity_difference',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='continuity_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='continuity_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('awaiting_predecessor', 'Awaiting Predecessor'), ('conflict', 'Continuity Conflict'), ('exception', 'Manual Exception')], default='valid', max_length=30),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='expected_opening_reading',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='is_conflict_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeshiftcollection',
            name='collection_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('fleet_card', 'Fleet Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeshiftdeduction',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshiftdeduction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shiftnozzlemeter',
            name='opening_source',
            field=models.CharField(choices=[('previous_shift', 'Previous Shift'), ('previous_shift_card', 'Previous Shift Card'), ('commissioning', 'Nozzle Commissioning'), ('opening_balance', 'Opening Balance'), ('initial_opening_balance', 'Initial Opening Balance'), ('physical_slip_missing_predecessor', 'Physical Slip (Missing Predecessor)'), ('approved_correction', 'Approved Correction'), ('meter_reset_or_replacement', 'Meter Reset/Replacement'), ('manual_exception', 'Manual Exception')], default='previous_shift', max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftnozzlemeter',
            name='staff_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_meters', to='shifts.operationalshiftstaff'),
        ),
        migrations.CreateModel(
            name='EmployeeShiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('actual_starts_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ends_at', models.DateTimeField(blank=True, null=True)),
                ('mpd_slip_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mpd_slip_attachment', models.FileField(blank=True, null=True, upload_to='mpd_slips/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('void', 'Void')], default='active', max_length=20)),
                ('is_shortage_excess_acknowledged', models.BooleanField(default=False)),
                ('shortage_excess_acknowledgement_note', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_cards', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_cards', to='employees.employee')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_cards', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_cards', to='organizations.outlet')),
                ('parent_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_cards', to='shifts.operationalshift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shift_cards', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_shift_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='collectionauditlog',
            name='shift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_audit_logs', to='shifts.employeeshiftcard'),
        ),
        migrations.AddField(
            model_name='employeeshiftcollection',
            name='shift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shifts.employeeshiftcard'),
        ),
        migrations.AddField(
            model_name='employeeshiftdeduction',
            name='shift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='shifts.employeeshiftcard'),
        ),
        migrations.AddField(
            model_name='employeeshiftsettlement',
            name='shift_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='shifts.employeeshiftcard'),
        ),
        migrations.AddField(
            model_name='fuelcreditslip',
            name='shift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_slips', to='shifts.employeeshiftcard'),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='shift_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='shifts.employeeshiftcard'),
        ),
        migrations.AddConstraint(
            model_name='employeeshiftcard',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('parent_shift', 'employee'), name='unique_active_parent_shift_employee_card'),
        ),
    ]
