# Generated by Django 5.2.17 on 2026-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_employeeshiftdeduction_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftnozzlemeter',
            name='opening_source',
            field=models.CharField(choices=[('previous_shift_card', 'Previous Shift Card'), ('previous_shift', 'Previous Shift'), ('commissioning', 'Nozzle Commissioning'), ('initial_opening_balance', 'Initial Opening Balance'), ('opening_balance', 'Opening Balance'), ('physical_slip_missing_predecessor', 'Physical Slip (Missing Predecessor)'), ('approved_correction', 'Approved Correction'), ('meter_reset_or_replacement', 'Meter Reset/Replacement'), ('manual_exception', 'Manual Exception')], default='previous_shift_card', max_length=50),
        ),
    ]
