# Generated by Django 5.2.17 on 2026-09-09 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('shifts', '0010_alter_shiftnozzlemeter_opening_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_nozzle_meters', to='forecourt.fuelproduct'),
        ),
        migrations.AddField(
            model_name='shiftnozzlemeter',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_nozzle_meters', to='forecourt.tank'),
        ),
    ]
