# Generated by Django 5.2.17 on 2026-09-10 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_shiftnozzlemeter_product_shiftnozzlemeter_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcreditslip',
            name='is_credit_limit_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fuelcreditslip',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shiftdefinition',
            name='effective_from',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
        migrations.AddField(
            model_name='shiftdefinition',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifttankdipobservation',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
