# Generated by Django 5.2.17 on 2026-09-14 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0019_seed_supplier_payment_permissions'),
        ('purchases', '0006_productpurchasetaxmapping_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('organisation', 'outlet', 'client_request_id'), name='unique_supplier_payment_client_request'),
        ),
    ]
