# Generated by Django 5.2.17 on 2026-09-15 04:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_supplier_payment_sources(apps, schema_editor):
    Movement = apps.get_model('finance', 'PaymentAccountMovement')
    for movement in Movement.objects.filter(payment_id__isnull=False, source_id__isnull=True).iterator():
        movement.source_type = 'supplier_payment'
        movement.source_id = movement.payment_id
        movement.save(update_fields=['source_type', 'source_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_supplierpayment_client_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccountmovement',
            name='source_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccountmovement',
            name='source_type',
            field=models.CharField(default='supplier_payment', max_length=50),
        ),
        migrations.RunPython(backfill_supplier_payment_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paymentaccountmovement',
            name='movement_type',
            field=models.CharField(choices=[('supplier_payment', 'Supplier Payment'), ('supplier_payment_reversal', 'Supplier Payment Reversal'), ('sales_invoice_receipt', 'Sales Invoice Receipt'), ('sales_invoice_receipt_reversal', 'Sales Invoice Receipt Reversal')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentaccountmovement',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_movements', to='finance.supplierpayment'),
        ),
    ]
