# Generated by Django 5.2.17 on 2026-09-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentaccountmovement_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccountmovement',
            name='movement_type',
            field=models.CharField(choices=[('supplier_payment', 'Supplier Payment'), ('supplier_payment_reversal', 'Supplier Payment Reversal'), ('sales_invoice_receipt', 'Sales Invoice Receipt'), ('sales_invoice_receipt_reversal', 'Sales Invoice Receipt Reversal'), ('customer_receipt', 'Customer Receipt'), ('customer_receipt_reversal', 'Customer Receipt Reversal')], max_length=40),
        ),
    ]
