# Generated by Django 5.2.17 on 2026-09-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_chart_and_permissions'),
        ('finance', '0004_alter_paymentaccountmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='ledger_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_account', to='accounting.chartofaccount'),
        ),
    ]
