# Generated by Django 5.2 on 2026-09-16

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounting', '0003_seed_supplier_advances'),
        ('finance', '0007_supplierpaymentallocation_is_advance_application'),
        ('organizations', '0020_seed_sales_and_item_stock_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccountmovement', name='movement_type',
            field=models.CharField(max_length=40, choices=[
                ('supplier_payment', 'Supplier Payment'), ('supplier_payment_reversal', 'Supplier Payment Reversal'),
                ('sales_invoice_receipt', 'Sales Invoice Receipt'), ('sales_invoice_receipt_reversal', 'Sales Invoice Receipt Reversal'),
                ('customer_receipt', 'Customer Receipt'), ('customer_receipt_reversal', 'Customer Receipt Reversal'),
                ('expense', 'Expense'), ('expense_reversal', 'Expense Reversal'),
                ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'),
                ('transfer_out_reversal', 'Transfer Out Reversal'), ('transfer_in_reversal', 'Transfer In Reversal'),
            ]),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)), ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)), ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_categories', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_categories', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounting.chartofaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='organizations.organisation')),
            ], options={'ordering': ['display_order', 'name']},
        ),
        migrations.CreateModel(
            name='ExpenseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()), ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='CashBankTransferSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()), ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank_transfer_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(max_length=100)), ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('expense_date', models.DateField(db_index=True)), ('category_code_snapshot', models.CharField(max_length=50)),
                ('category_name_snapshot', models.CharField(max_length=150)), ('ledger_code_snapshot', models.CharField(max_length=50)),
                ('ledger_name_snapshot', models.CharField(max_length=150)), ('payee', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)), ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to='accounting.chartofaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organizations.outlet')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.paymentaccount')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to=settings.AUTH_USER_MODEL)),
            ], options={'ordering': ['-expense_date', '-created_at']},
        ),
        migrations.CreateModel(
            name='CashBankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=100)), ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('transfer_date', models.DateField(db_index=True)), ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)), ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='finance.paymentaccount')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank_transfers', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank_transfers', to='organizations.outlet')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='finance.paymentaccount')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_cash_bank_transfers', to=settings.AUTH_USER_MODEL)),
            ], options={'ordering': ['-transfer_date', '-created_at']},
        ),
        migrations.AddConstraint('expensecategory', models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_org_expense_category_code_ci')),
        migrations.AddConstraint('expense', models.UniqueConstraint(fields=('outlet', 'expense_number'), name='unique_outlet_expense_number')),
        migrations.AddConstraint('expense', models.UniqueConstraint(condition=models.Q(client_request_id__isnull=False), fields=('organisation', 'outlet', 'client_request_id'), name='unique_expense_client_request')),
        migrations.AddConstraint('expense', models.CheckConstraint(condition=models.Q(amount__gt=0), name='expense_amount_positive')),
        migrations.AddConstraint('expensesequence', models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_expense_seq_year')),
        migrations.AddConstraint('cashbanktransfer', models.UniqueConstraint(fields=('outlet', 'transfer_number'), name='unique_outlet_cash_bank_transfer_number')),
        migrations.AddConstraint('cashbanktransfer', models.UniqueConstraint(condition=models.Q(client_request_id__isnull=False), fields=('organisation', 'outlet', 'client_request_id'), name='unique_transfer_client_request')),
        migrations.AddConstraint('cashbanktransfer', models.CheckConstraint(condition=models.Q(amount__gt=0), name='cash_bank_transfer_amount_positive')),
        migrations.AddConstraint('cashbanktransfer', models.CheckConstraint(condition=~models.Q(from_account=models.F('to_account')), name='cash_bank_transfer_different_accounts')),
        migrations.AddConstraint('cashbanktransfersequence', models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_transfer_seq_year')),
    ]
