# Generated by Django 5.2.17 on 2026-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_digital_settlements'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsettlement',
            name='accounting_basis',
            field=models.CharField(choices=[('legacy_sales', 'Legacy Sales Posting'), ('clearing', 'Digital Collection Clearing')], default='legacy_sales', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentaccountmovement',
            name='movement_type',
            field=models.CharField(choices=[('supplier_payment', 'Supplier Payment'), ('supplier_payment_reversal', 'Supplier Payment Reversal'), ('sales_invoice_receipt', 'Sales Invoice Receipt'), ('sales_invoice_receipt_reversal', 'Sales Invoice Receipt Reversal'), ('customer_receipt', 'Customer Receipt'), ('customer_receipt_reversal', 'Customer Receipt Reversal'), ('expense', 'Expense'), ('expense_reversal', 'Expense Reversal'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('transfer_out_reversal', 'Transfer Out Reversal'), ('transfer_in_reversal', 'Transfer In Reversal'), ('digital_settlement', 'Digital Settlement'), ('digital_settlement_reversal', 'Digital Settlement Reversal'), ('shift_cash_collection', 'Shift Cash Collection'), ('shift_cash_collection_reversal', 'Shift Cash Collection Reversal')], max_length=40),
        ),
        migrations.AlterField(
            model_name='digitalsettlement',
            name='accounting_basis',
            field=models.CharField(choices=[('legacy_sales', 'Legacy Sales Posting'), ('clearing', 'Digital Collection Clearing')], default='clearing', max_length=20),
        ),
    ]
