from django.urls import path

from .views import (
    CashBankTransferDetailView,
    CashBankTransferListCreateView,
    CashBankTransferVoidView,
    ExpenseCategoryDeactivateView,
    ExpenseCategoryDetailView,
    ExpenseCategoryListCreateView,
    ExpenseDetailView,
    ExpenseListCreateView,
    ExpenseVoidView,
    DigitalSettlementDetailView,
    DigitalSettlementListCreateView,
    DigitalSettlementVoidView,
    PendingDigitalCollectionListView,
    PaymentAccountBookView,
    PaymentAccountDeactivateView,
    PaymentAccountDetailView,
    PaymentAccountListCreateView,
    PaymentAccountOptionsView,
    SupplierOpenBillsView,
    SupplierPaymentAllocateView,
    SupplierPaymentDetailView,
    SupplierPaymentListCreateView,
    SupplierPaymentVoidView,
)

urlpatterns = [
    path('<uuid:org_id>/expense-categories/', ExpenseCategoryListCreateView.as_view(), name='expense_category_list_create'),
    path('<uuid:org_id>/expense-categories/<uuid:category_id>/', ExpenseCategoryDetailView.as_view(), name='expense_category_detail'),
    path('<uuid:org_id>/expense-categories/<uuid:category_id>/deactivate/', ExpenseCategoryDeactivateView.as_view(), name='expense_category_deactivate'),
    path('<uuid:org_id>/payment-accounts/', PaymentAccountListCreateView.as_view(), name='payment_account_list_create'),
    path('<uuid:org_id>/payment-accounts/<uuid:account_id>/', PaymentAccountDetailView.as_view(), name='payment_account_detail'),
    path('<uuid:org_id>/payment-accounts/<uuid:account_id>/deactivate/', PaymentAccountDeactivateView.as_view(), name='payment_account_deactivate'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/payment-accounts/options/', PaymentAccountOptionsView.as_view(), name='payment_account_options'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/payment-accounts/<uuid:account_id>/book/', PaymentAccountBookView.as_view(), name='payment_account_book'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/expenses/', ExpenseListCreateView.as_view(), name='expense_list_create'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/expenses/<uuid:expense_id>/', ExpenseDetailView.as_view(), name='expense_detail'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/expenses/<uuid:expense_id>/void/', ExpenseVoidView.as_view(), name='expense_void'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/cash-bank-transfers/', CashBankTransferListCreateView.as_view(), name='cash_bank_transfer_list_create'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/cash-bank-transfers/<uuid:transfer_id>/', CashBankTransferDetailView.as_view(), name='cash_bank_transfer_detail'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/cash-bank-transfers/<uuid:transfer_id>/void/', CashBankTransferVoidView.as_view(), name='cash_bank_transfer_void'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/digital-settlements/pending-collections/', PendingDigitalCollectionListView.as_view(), name='pending_digital_collections'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/digital-settlements/', DigitalSettlementListCreateView.as_view(), name='digital_settlement_list_create'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/digital-settlements/<uuid:settlement_id>/', DigitalSettlementDetailView.as_view(), name='digital_settlement_detail'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/digital-settlements/<uuid:settlement_id>/void/', DigitalSettlementVoidView.as_view(), name='digital_settlement_void'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/supplier-payments/', SupplierPaymentListCreateView.as_view(), name='supplier_payment_list_create'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/supplier-payments/<uuid:payment_id>/', SupplierPaymentDetailView.as_view(), name='supplier_payment_detail'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/supplier-payments/<uuid:payment_id>/allocations/', SupplierPaymentAllocateView.as_view(), name='supplier_payment_allocate'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/supplier-payments/<uuid:payment_id>/void/', SupplierPaymentVoidView.as_view(), name='supplier_payment_void'),
    path('<uuid:org_id>/outlets/<uuid:outlet_id>/suppliers/<uuid:supplier_id>/open-purchase-bills/', SupplierOpenBillsView.as_view(), name='supplier_open_purchase_bills'),
]
