import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,CheckCircle2,WandSparkles}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{useAppSelector}from'@/app/store';
import{PageHeader}from'@/components/navigation/PageHeader';
import{createCustomerReceipt,fetchCustomerOpenSalesInvoices,fetchCustomers,fetchPaymentAccountOptions,type Customer}from'@/api/client';
import type{PaymentAccount}from'@/features/finance/types';
import type{OpenSalesInvoice}from'@/features/sales/types';
const today=()=>new Date().toISOString().slice(0,10); const money=(v:string|number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0));
export const CustomerReceiptFormPage:React.FC=()=>{
 const navigate=useNavigate();const orgId=useAppSelector(s=>s.ui.selectedOrganizationId);const outletId=useAppSelector(s=>s.ui.selectedOutletId);
 const[customers,setCustomers]=useState<Customer[]>([]);const[accounts,setAccounts]=useState<PaymentAccount[]>([]);const[invoices,setInvoices]=useState<OpenSalesInvoice[]>([]);const[allocations,setAllocations]=useState<Record<string,string>>({});const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[requestId]=useState(()=>crypto.randomUUID());
 const[form,setForm]=useState({customer_id:'',receipt_date:today(),amount:'',payment_method:'cash',payment_account_id:'',reference_number:'',notes:''});
 useEffect(()=>{if(orgId&&outletId)Promise.all([fetchCustomers(orgId,{status:'active'}),fetchPaymentAccountOptions(orgId,outletId)]).then(([c,a])=>{setCustomers(c);setAccounts(a)}).catch(e=>setError(e.message));},[orgId,outletId]);
 useEffect(()=>{if(!orgId||!outletId||!form.customer_id){setInvoices([]);setAllocations({});return}fetchCustomerOpenSalesInvoices(orgId,outletId,form.customer_id).then(setInvoices).catch(e=>setError(e.message));},[orgId,outletId,form.customer_id]);
 const amount=Number(form.amount)||0;const allocated=useMemo(()=>Object.values(allocations).reduce((s,v)=>s+(Number(v)||0),0),[allocations]);const accountsForMethod=accounts.filter(a=>form.payment_method==='cash'?a.account_type==='cash':a.account_type==='bank');
 const autoAllocate=()=>{let remaining=amount;const next:Record<string,string>={};for(const invoice of invoices){if(remaining<=0)break;const value=Math.min(remaining,Number(invoice.outstanding_amount));if(value>0)next[invoice.id]=value.toFixed(2);remaining-=value}setAllocations(next)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!orgId||!outletId)return;if(allocated>amount){setError('Allocations exceed receipt amount.');return}setSaving(true);setError(null);try{const receipt=await createCustomerReceipt(orgId,outletId,{...form,client_request_id:requestId,allocations:Object.entries(allocations).filter(([,v])=>Number(v)>0).map(([sales_invoice_id,v])=>({sales_invoice_id,amount:v}))});navigate('/app/sales/receipts',{state:{receipt}})}catch(err:any){setError(err.message);setSaving(false)}};
 return <form onSubmit={submit} style={{maxWidth:1450,margin:'0 auto',padding:'1.5rem'}}><button type="button" className="btn btn-ghost" onClick={()=>navigate('/app/sales/receipts')}><ArrowLeft size={16}/> Back</button><PageHeader title="Record Customer Receipt" subtitle="Allocate a collection to open invoices; any remainder is retained as customer advance."/>{error&&<div className="alert alert-error">{error}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 330px',gap:20,alignItems:'start'}}><div style={{display:'grid',gap:18}}><section className="card" style={{padding:20}}><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14}}>
 <label>Customer<select className="input" required value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.display_name} ({c.customer_code})</option>)}</select></label><label>Receipt Date<input className="input" type="date" required value={form.receipt_date} onChange={e=>setForm({...form,receipt_date:e.target.value})}/></label><label>Amount<input className="input" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Method<select className="input" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value,payment_account_id:''})}><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="upi">UPI</option><option value="card">Card</option></select></label><label>Deposit Account<select className="input" required value={form.payment_account_id} onChange={e=>setForm({...form,payment_account_id:e.target.value})}><option value="">Select account</option>{accountsForMethod.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Reference<input className="input" value={form.reference_number} onChange={e=>setForm({...form,reference_number:e.target.value})}/></label><label style={{gridColumn:'1/-1'}}>Notes<textarea className="input" rows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></section>
 <section className="card" style={{overflow:'hidden'}}><div style={{padding:18,display:'flex',justifyContent:'space-between'}}><div><h3 style={{margin:0}}>Open Sales Invoices</h3><div className="text-muted">Allocate oldest invoices first or enter amounts manually.</div></div><button type="button" className="btn btn-secondary" disabled={!amount} onClick={autoAllocate}><WandSparkles size={16}/> Auto Allocate</button></div><table className="data-table"><thead><tr><th>Invoice</th><th>Date</th><th>Due</th><th style={{textAlign:'right'}}>Outstanding</th><th>Allocate</th></tr></thead><tbody>{!form.customer_id?<tr><td colSpan={5} style={{textAlign:'center',padding:30}}>Select a customer.</td></tr>:invoices.length===0?<tr><td colSpan={5} style={{textAlign:'center',padding:30}}>No open invoices.</td></tr>:invoices.map(i=><tr key={i.id}><td><strong>{i.invoice_number}</strong></td><td>{i.invoice_date}</td><td>{i.due_date}</td><td style={{textAlign:'right'}}>{money(i.outstanding_amount)}</td><td><input aria-label={`Allocate ${i.invoice_number}`} className="input" type="number" min="0" step="0.01" max={i.outstanding_amount} value={allocations[i.id]||''} onChange={e=>setAllocations({...allocations,[i.id]:e.target.value})}/></td></tr>)}</tbody></table></section></div>
 <aside className="card" style={{padding:20,position:'sticky',top:20}}><h3 style={{marginTop:0}}>Receipt Summary</h3>{[['Amount',money(amount)],['Allocated',money(allocated)],['Customer Advance',money(Math.max(0,amount-allocated))]].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--border-color)'}}><span>{l}</span><strong>{v}</strong></div>)}<button className="btn btn-primary" style={{width:'100%',justifyContent:'center',marginTop:18}} disabled={saving||amount<=0||allocated>amount||!form.customer_id||!form.payment_account_id}><CheckCircle2 size={16}/>{saving?' Saving…':' Save Receipt'}</button></aside></div></form>;
};
