# Generated by Django 5.2.17 on 2026-08-24 17:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_seed_forecourt_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensers', to='organizations.outlet')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FuelProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('premium_petrol', 'Premium Petrol'), ('premium_diesel', 'Premium Diesel'), ('cng', 'CNG'), ('adblue', 'AdBlue'), ('other', 'Other')], default='petrol', max_length=50)),
                ('custom_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(choices=[('litre', 'Litre'), ('kilogram', 'Kilogram')], default='litre', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_products', to='organizations.organisation')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prices', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='organizations.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='forecourt.fuelproduct')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('safe_fill_capacity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('dead_stock_level', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('commissioned_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='organizations.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='forecourt.fuelproduct')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('nozzle_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='forecourt.dispenser')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzles', to='organizations.outlet')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='forecourt.tank')),
            ],
            options={
                'ordering': ['dispenser', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='dispenser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('outlet'), name='unique_outlet_dispenser_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='fuelproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organisation'), name='unique_organisation_fuel_product_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='fuelproduct',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organisation'), name='unique_organisation_fuel_product_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='tank',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('outlet'), name='unique_outlet_tank_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='nozzle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('outlet'), name='unique_outlet_nozzle_code_case_insensitive'),
        ),
    ]
