# Generated by Django 5.2.17 on 2026-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='acknowledged_manual_dip',
            field=models.BooleanField(default=False),
        ),
    ]
