# Generated by Django 5.2.17 on 2026-09-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecourt', '0002_tank_acknowledged_manual_dip'),
        ('inventory', '0005_item_tankstockmovement_item_unitmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelproduct',
            name='canonical_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_fuel_product', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_for_item', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='tank',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='inventory.item'),
        ),
    ]
