import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAppSelector } from '@/app/store';
import { PageHeader } from '@/components/navigation/PageHeader';
import { createCashBankTransfer, fetchPaymentAccountOptions } from '@/api/client';
import type { PaymentAccount } from '@/features/finance/types';

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0));
export const CashBankTransferFormPage: React.FC = () => {
  const navigate = useNavigate(); const orgId = useAppSelector((s) => s.ui.selectedOrganizationId); const outletId = useAppSelector((s) => s.ui.selectedOutletId);
  const [accounts, setAccounts] = useState<PaymentAccount[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [requestId] = useState(() => crypto.randomUUID());
  const [form, setForm] = useState({ transfer_date: today(), from_account_id: '', to_account_id: '', amount: '', reference_number: '', notes: '' });
  useEffect(() => { if (orgId && outletId) fetchPaymentAccountOptions(orgId, outletId).then(setAccounts).catch((e) => setError(e.message)); }, [orgId, outletId]);
  const from = accounts.find((a) => a.id === form.from_account_id); const to = accounts.find((a) => a.id === form.to_account_id);
  const transferLabel = useMemo(() => !from || !to ? 'Cash / Bank Transfer' : from.account_type === 'cash' && to.account_type === 'bank' ? 'Cash Deposit' : from.account_type === 'bank' && to.account_type === 'cash' ? 'Bank Withdrawal' : 'Account Transfer', [from, to]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!orgId || !outletId) return; setSaving(true); setError(null); try { const row = await createCashBankTransfer(orgId, outletId, { ...form, client_request_id: requestId }); navigate(`/app/finance/transfers/${row.id}`); } catch (e: any) { setError(e?.data?.detail || Object.values(e?.data || {}).flat().join(' ') || e.message); } finally { setSaving(false); } };
  return <form onSubmit={submit} style={{ maxWidth: 1200, margin: '0 auto', padding: '1.5rem' }}><PageHeader title="New Cash / Bank Transfer" subtitle="Record a cash deposit, bank withdrawal or movement between accounts." actions={<button type="button" className="btn btn-secondary" onClick={() => navigate('/app/finance/cash-banking')}><ArrowLeft size={16}/> Back</button>}/>{error && <div className="alert alert-error" style={{ marginBottom: 16 }}>{error}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(300px,.8fr)', gap: 20, alignItems: 'start' }}><section className="card" style={{ padding: 24 }}><h3 style={{ marginTop: 0 }}>Transfer Details</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 16 }}><label>Transfer Date<input className="input" type="date" required value={form.transfer_date} onChange={(e) => setForm({ ...form, transfer_date: e.target.value })}/></label><label>Amount<input className="input" type="number" min="0.01" step="0.01" required value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })}/></label><label>From Account<select className="input" required value={form.from_account_id} onChange={(e) => setForm({ ...form, from_account_id: e.target.value })}><option value="">Select source</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name} · {money(a.current_balance)}</option>)}</select></label><label>To Account<select className="input" required value={form.to_account_id} onChange={(e) => setForm({ ...form, to_account_id: e.target.value })}><option value="">Select destination</option>{accounts.filter((a) => a.id !== form.from_account_id).map((a) => <option key={a.id} value={a.id}>{a.name} · {money(a.current_balance)}</option>)}</select></label><label>Reference Number<input className="input" value={form.reference_number} onChange={(e) => setForm({ ...form, reference_number: e.target.value })}/></label><label style={{ gridColumn: '1 / -1' }}>Notes<textarea className="input" rows={4} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label></div></section><aside className="card" style={{ padding: 22, position: 'sticky', top: 20 }}><h3 style={{ marginTop: 0 }}>{transferLabel}</h3><div style={{ display: 'flex', alignItems: 'center', gap: 10, margin: '18px 0' }}><strong>{from?.name || 'From account'}</strong><ArrowRight size={18}/><strong>{to?.name || 'To account'}</strong></div><div style={{ fontSize: 24, fontWeight: 800 }}>{money(form.amount)}</div><p className="text-muted">Both account balances and the general ledger update together.</p><button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center' }} disabled={saving || !from || !to || from.id === to.id || Number(form.amount) <= 0}><CheckCircle2 size={17}/>{saving ? ' Saving…' : ' Save Transfer'}</button></aside></div>
  </form>;
};
