import React, { useEffect, useState } from 'react';
import { ArrowLeft, Ban, BookOpen } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAppSelector } from '@/app/store';
import { PageHeader } from '@/components/navigation/PageHeader';
import { fetchDigitalSettlement, voidDigitalSettlement } from '@/api/client';
import type { DigitalSettlement } from '@/features/finance/types';

const money = (value: string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0));
export const DigitalSettlementDetailPage: React.FC = () => {
  const { settlementId } = useParams(); const navigate = useNavigate(); const orgId = useAppSelector((s) => s.ui.selectedOrganizationId); const outletId = useAppSelector((s) => s.ui.selectedOutletId);
  const [row, setRow] = useState<DigitalSettlement | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (orgId && outletId && settlementId) fetchDigitalSettlement(orgId, outletId, settlementId).then(setRow).catch((e) => setError(e?.data?.detail || e.message)); }, [orgId, outletId, settlementId]);
  const voidRow = async () => { if (!orgId || !outletId || !settlementId) return; const reason = window.prompt('Reason for voiding this settlement (minimum 5 characters):'); if (!reason) return; try { setRow(await voidDigitalSettlement(orgId, outletId, settlementId, reason)); } catch (e: any) { setError(e?.data?.detail || Object.values(e?.data || {}).flat().join(' ') || e.message); } };
  if (!row) return <div className="card" style={{ margin: 24, padding: 32 }}>{error || 'Loading settlement…'}</div>;
  return <div style={{ maxWidth: 1250, margin: '0 auto', padding: '1.5rem' }}><PageHeader title={row.settlement_number} subtitle="Recorded digital settlement — bank movement and journal are immutable." actions={<div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary" onClick={() => navigate('/app/finance/settlements')}><ArrowLeft size={16}/> Back</button>{row.accounting_journal_id && <button className="btn btn-secondary" onClick={() => navigate(`/app/finance/vouchers/${row.accounting_journal_id}`)}><BookOpen size={16}/> View Journal</button>}{row.status === 'active' && <button className="btn btn-danger" onClick={voidRow}><Ban size={16}/> Void</button>}</div>}/>{error && <div className="alert alert-error">{error}</div>}{row.status === 'voided' && <div className="alert alert-warning" style={{ marginBottom: 16 }}>Voided: {row.void_reason}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(280px,.75fr)', gap: 20, alignItems: 'start' }}><div style={{ display: 'grid', gap: 18 }}><section className="card" style={{ padding: 22 }}><h3 style={{ marginTop: 0 }}>Settlement Details</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 20 }}>{[
      ['Date', row.settlement_date], ['Provider', row.provider_name], ['Method', row.collection_method_display], ['Bank Account', row.payment_account_name], ['Bank Reference', row.bank_reference], ['Provider Batch', row.batch_reference || '—'], ['Status', row.status], ['Recorded By', row.created_by_name || '—'], ['Collections', String(row.allocations.length)],
    ].map(([label,value]) => <div key={label}><div className="text-muted">{label}</div><strong>{value}</strong></div>)}</div>{row.notes && <p style={{ marginBottom: 0, marginTop: 20 }}>{row.notes}</p>}</section>
      <section className="card" style={{ overflow: 'hidden' }}><div style={{ padding: 18 }}><h3 style={{ margin: 0 }}>Matched Shift Collections</h3></div><table className="data-table"><thead><tr><th>Date</th><th>Employee</th><th>Reference</th><th style={{ textAlign: 'right' }}>Amount</th></tr></thead><tbody>{row.allocations.map((item) => <tr key={item.id}><td>{new Date(item.occurred_at_snapshot).toLocaleDateString('en-IN')}</td><td>{item.employee_name_snapshot}</td><td>{item.collection_reference_snapshot || '—'}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{money(item.amount)}</td></tr>)}</tbody></table></section></div>
      <aside className="card" style={{ padding: 22 }}><h3 style={{ marginTop: 0 }}>Amounts</h3>{[['Gross Collection', row.gross_amount], ['Gateway Charges', row.charges_amount], ['TDS Deducted', row.tds_amount]].map(([label,value]) => <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid var(--border-color)' }}><span className="text-muted">{label}</span><strong>{money(value)}</strong></div>)}<div style={{ display: 'flex', justifyContent: 'space-between', padding: '17px 0', fontSize: 18 }}><span>Net Bank Credit</span><strong>{money(row.net_amount)}</strong></div></aside></div>
  </div>;
};
