import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAppSelector } from '@/app/store';
import { PageHeader } from '@/components/navigation/PageHeader';
import { createDigitalSettlement, fetchPaymentAccountOptions, fetchPendingDigitalCollections } from '@/api/client';
import type { PaymentAccount, PendingDigitalCollection } from '@/features/finance/types';

const today = () => new Date().toISOString().slice(0, 10);
const money = (value: string | number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0));
const methodName = (value: string) => ({ card: 'Card', upi: 'UPI', fleet_card: 'Fleet Card' }[value] || value);

export const DigitalSettlementFormPage: React.FC = () => {
  const navigate = useNavigate(); const orgId = useAppSelector((s) => s.ui.selectedOrganizationId); const outletId = useAppSelector((s) => s.ui.selectedOutletId);
  const [collections, setCollections] = useState<PendingDigitalCollection[]>([]); const [accounts, setAccounts] = useState<PaymentAccount[]>([]); const [groupKey, setGroupKey] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [requestId] = useState(() => crypto.randomUUID());
  const [form, setForm] = useState({ settlement_date: today(), payment_account_id: '', charges_amount: '0.00', tds_amount: '0.00', batch_reference: '', bank_reference: '', notes: '' });
  useEffect(() => { if (orgId && outletId) Promise.all([fetchPendingDigitalCollections(orgId, outletId), fetchPaymentAccountOptions(orgId, outletId)]).then(([rows, accountRows]) => { setCollections(rows); setAccounts(accountRows.filter((row) => row.account_type === 'bank')); }).catch((e) => setError(e?.data?.detail || e.message)); }, [orgId, outletId]);
  const groups = useMemo(() => { const map = new Map<string, { method: string; provider: string; count: number; total: number }>(); collections.forEach((row) => { const provider = row.provider_name?.trim() || 'Unspecified'; const key = `${row.collection_method}|${provider.toLowerCase()}`; const current = map.get(key) || { method: row.collection_method, provider, count: 0, total: 0 }; current.count += 1; current.total += Number(row.amount); map.set(key, current); }); return Array.from(map.entries()); }, [collections]);
  const visible = collections.filter((row) => { const provider = row.provider_name?.trim() || 'Unspecified'; return `${row.collection_method}|${provider.toLowerCase()}` === groupKey; });
  const gross = visible.filter((row) => selected.includes(row.id)).reduce((sum,row) => sum + Number(row.amount), 0); const charges = Number(form.charges_amount) || 0; const tds = Number(form.tds_amount) || 0; const net = gross - charges - tds;
  const chooseGroup = (key: string) => { setGroupKey(key); setSelected([]); };
  const toggleAll = () => setSelected(selected.length === visible.length ? [] : visible.map((row) => row.id));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!orgId || !outletId) return; setSaving(true); setError(null); try { const row = await createDigitalSettlement(orgId, outletId, { ...form, client_request_id: requestId, collection_ids: selected }); navigate(`/app/finance/settlements/${row.id}`); } catch (e: any) { setError(e?.data?.detail || Object.values(e?.data || {}).flat().join(' ') || e.message); } finally { setSaving(false); } };
  if (!orgId || !outletId) return <div className="card" style={{ margin: 24, padding: 32 }}>Select an organisation and outlet before recording a settlement.</div>;
  return <form onSubmit={submit} style={{ maxWidth: 1450, margin: '0 auto', padding: '1.5rem' }}><PageHeader title="Record Digital Settlement" subtitle="Select pending collections from one provider and record the exact bank credit." actions={<button type="button" className="btn btn-secondary" onClick={() => navigate('/app/finance/settlements')}><ArrowLeft size={16}/> Back</button>}/>{error && <div className="alert alert-error" style={{ marginBottom: 16 }}>{error}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(320px,.8fr)', gap: 20, alignItems: 'start' }}><div style={{ display: 'grid', gap: 18 }}><section className="card" style={{ padding: 20 }}><h3 style={{ marginTop: 0 }}>Settlement Source</h3><label>Provider and Method<select className="input" required value={groupKey} onChange={(e) => chooseGroup(e.target.value)}><option value="">Select pending collection group</option>{groups.map(([key, group]) => <option key={key} value={key}>{group.provider} · {methodName(group.method)} · {group.count} collections · {money(group.total)}</option>)}</select></label></section>
      <section className="card" style={{ overflow: 'hidden' }}><div style={{ padding: 18, display: 'flex', justifyContent: 'space-between' }}><div><h3 style={{ margin: 0 }}>Pending Shift Collections</h3><div className="text-muted">Only collections from the selected provider and method are shown.</div></div>{visible.length > 0 && <button type="button" className="btn btn-secondary" onClick={toggleAll}>{selected.length === visible.length ? 'Clear All' : 'Select All'}</button>}</div><table className="data-table"><thead><tr><th></th><th>Date</th><th>Employee</th><th>Reference</th><th>Terminal / Account</th><th style={{ textAlign: 'right' }}>Amount</th></tr></thead><tbody>{visible.length === 0 ? <tr><td colSpan={6} style={{ textAlign: 'center', padding: 36 }}>{groupKey ? 'No pending collections in this group.' : 'Select a provider group.'}</td></tr> : visible.map((row) => <tr key={row.id}><td><input aria-label={`Select collection ${row.id}`} type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected(selected.includes(row.id) ? selected.filter((id) => id !== row.id) : [...selected, row.id])}/></td><td>{new Date(row.occurred_at).toLocaleDateString('en-IN')}</td><td>{row.employee_name}</td><td>{row.reference_number || '—'}</td><td>{row.terminal_or_account_reference || '—'}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{money(row.amount)}</td></tr>)}</tbody></table></section>
      <section className="card" style={{ padding: 20 }}><h3 style={{ marginTop: 0 }}>Bank Credit Details</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 15 }}><label>Settlement Date<input className="input" type="date" required value={form.settlement_date} onChange={(e) => setForm({ ...form, settlement_date: e.target.value })}/></label><label>Bank Account<select className="input" required value={form.payment_account_id} onChange={(e) => setForm({ ...form, payment_account_id: e.target.value })}><option value="">Select bank account</option>{accounts.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Provider Batch Reference<input className="input" value={form.batch_reference} onChange={(e) => setForm({ ...form, batch_reference: e.target.value })}/></label><label>Bank Reference<input className="input" required value={form.bank_reference} onChange={(e) => setForm({ ...form, bank_reference: e.target.value })}/></label><label>Gateway Charges<input className="input" type="number" min="0" step="0.01" value={form.charges_amount} onChange={(e) => setForm({ ...form, charges_amount: e.target.value })}/></label><label>TDS Deducted<input className="input" type="number" min="0" step="0.01" value={form.tds_amount} onChange={(e) => setForm({ ...form, tds_amount: e.target.value })}/></label><label style={{ gridColumn: '1 / -1' }}>Notes<textarea className="input" rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })}/></label></div></section></div>
      <aside className="card" style={{ padding: 22, position: 'sticky', top: 20 }}><h3 style={{ marginTop: 0 }}>Settlement Summary</h3>{[['Collections', String(selected.length)], ['Gross Collection', money(gross)], ['Gateway Charges', money(charges)], ['TDS', money(tds)]].map(([label,value]) => <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '11px 0', borderBottom: '1px solid var(--border-color)' }}><span className="text-muted">{label}</span><strong>{value}</strong></div>)}<div style={{ display: 'flex', justifyContent: 'space-between', padding: '16px 0', fontSize: 19 }}><span>Net Bank Credit</span><strong>{money(net)}</strong></div>{net <= 0 && selected.length > 0 && <div className="alert alert-error">Net bank credit must be positive.</div>}<button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center' }} disabled={saving || selected.length === 0 || !form.payment_account_id || !form.bank_reference.trim() || net <= 0}><CheckCircle2 size={17}/>{saving ? ' Saving…' : ' Save Settlement'}</button></aside></div>
  </form>;
};
