import React, { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Ban, Plus } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAppSelector } from '@/app/store';
import { PageHeader } from '@/components/navigation/PageHeader';
import { allocateSupplierPayment, fetchSupplierOpenBills, fetchSupplierPayment, voidSupplierPayment } from '@/api/client';
import type { OpenPurchaseBill, SupplierPayment } from '@/features/finance/types';

const money = (value: string | number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(value || 0));

export const SupplierPaymentDetailPage: React.FC = () => {
  const navigate = useNavigate(); const { paymentId } = useParams();
  const orgId = useAppSelector((state) => state.ui.selectedOrganizationId); const outletId = useAppSelector((state) => state.ui.selectedOutletId);
  const [payment, setPayment] = useState<SupplierPayment | null>(null); const [bills, setBills] = useState<OpenPurchaseBill[]>([]);
  const [showAllocate, setShowAllocate] = useState(false); const [allocations, setAllocations] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!orgId || !outletId || !paymentId) return; try { const row = await fetchSupplierPayment(orgId, outletId, paymentId); setPayment(row); setError(null); } catch (err: any) { setError(err?.data?.detail || err.message); } }, [orgId, outletId, paymentId]);
  useEffect(() => { load(); }, [load]);
  const openAllocate = async () => { if (!orgId || !outletId || !payment) return; setBills(await fetchSupplierOpenBills(orgId, outletId, payment.supplier)); setShowAllocate(true); };
  const allocate = async () => { if (!orgId || !outletId || !payment) return; try { await allocateSupplierPayment(orgId, outletId, payment.id, Object.entries(allocations).filter(([, amount]) => Number(amount) > 0).map(([purchase_bill_id, amount]) => ({ purchase_bill_id, amount }))); setShowAllocate(false); setAllocations({}); await load(); } catch (err: any) { setError(err?.data?.detail || (err?.data && Object.values(err.data).flat().join(' ')) || err.message); } };
  const voidPayment = async () => { if (!orgId || !outletId || !payment) return; const reason = window.prompt('Reason for voiding this payment (minimum 5 characters):'); if (!reason) return; try { await voidSupplierPayment(orgId, outletId, payment.id, reason); await load(); } catch (err: any) { setError(err?.data?.detail || err.message); } };
  if (!payment) return <div style={{ padding: 28 }}>{error || 'Loading payment…'}</div>;
  const usedBillIds = new Set(payment.allocations.map((row) => row.purchase_bill));
  return <div style={{ maxWidth: 1300, margin: '0 auto', padding: '1.5rem' }}>
    <PageHeader title={payment.payment_number} subtitle={`${payment.supplier_name} · ${payment.payment_date}`} actions={<div style={{ display: 'flex', gap: 8 }}><button className="btn btn-secondary" onClick={() => navigate('/app/purchases/supplier-payments')}><ArrowLeft size={16}/> Back</button>{payment.status === 'active' && Number(payment.unallocated_amount) > 0 && <button className="btn btn-secondary" onClick={openAllocate}><Plus size={16}/> Allocate Balance</button>}{payment.status === 'active' && <button className="btn btn-danger" onClick={voidPayment}><Ban size={16}/> Void</button>}</div>}/>
    {error && <div className="alert alert-error" style={{ marginBottom: 16 }}>{error}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 20 }}><div style={{ display: 'grid', gap: 20 }}>
      <section className="card" style={{ padding: 22 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h3 style={{ marginTop: 0 }}>Payment Details</h3><span className={`status-badge ${payment.status === 'active' ? 'success' : 'danger'}`}>{payment.status}</span></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 18 }}>{[['Supplier', payment.supplier_name], ['Payment Account', payment.payment_account_name], ['Method', payment.payment_method.replace('_', ' ')], ['Reference', payment.reference_number || payment.cheque_number || '—'], ['Created By', payment.created_by_name || '—'], ['Payment Date', payment.payment_date]].map(([label, value]) => <div key={label}><div className="text-muted">{label}</div><strong style={{ textTransform: label === 'Method' ? 'capitalize' : undefined }}>{value}</strong></div>)}</div>{payment.notes && <p style={{ marginBottom: 0 }}>{payment.notes}</p>}{payment.void_reason && <div className="alert alert-error" style={{ marginTop: 16 }}>Voided: {payment.void_reason}</div>}</section>
      <section className="card" style={{ overflow: 'hidden' }}><div style={{ padding: 20 }}><h3 style={{ margin: 0 }}>Bill Allocations</h3></div><table className="data-table"><thead><tr><th>Purchase Bill</th><th>Supplier Invoice</th><th>Invoice Date</th><th style={{ textAlign: 'right' }}>Allocated</th></tr></thead><tbody>{payment.allocations.length === 0 ? <tr><td colSpan={4} style={{ textAlign: 'center', padding: 32 }}>No bills allocated. The full amount is a supplier advance.</td></tr> : payment.allocations.map((row) => <tr key={row.id}><td><strong>{row.bill_number}</strong></td><td>{row.supplier_invoice_number}</td><td>{row.invoice_date}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{money(row.amount)}</td></tr>)}</tbody></table></section>
      <section className="card" style={{ padding: 22 }}><h3 style={{ marginTop: 0 }}>Audit Trail</h3>{payment.audit_logs.map((event) => <div key={event.id} style={{ padding: '10px 0', borderBottom: '1px solid var(--border-color)' }}><strong style={{ textTransform: 'capitalize' }}>{event.event_type}</strong><div className="text-muted">{event.actor_name || 'System'} · {new Date(event.created_at).toLocaleString('en-IN')}</div>{event.reason && <div>{event.reason}</div>}</div>)}</section>
    </div><aside className="card" style={{ padding: 22, height: 'fit-content' }}><h3 style={{ marginTop: 0 }}>Summary</h3>{[['Payment Amount', payment.amount], ['Allocated', payment.allocated_amount], ['Supplier Advance', payment.unallocated_amount]].map(([label, value]) => <div key={label} style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 0', borderBottom: '1px solid var(--border-color)' }}><span className="text-muted">{label}</span><strong>{money(value)}</strong></div>)}<div style={{ marginTop: 16 }} className="text-muted">Account movement</div><strong>{money(payment.account_movements.reduce((sum, row) => sum + Number(row.signed_amount), 0))}</strong></aside></div>
    {showAllocate && <div className="modal-overlay" onClick={() => setShowAllocate(false)}><div className="modal-content" style={{ maxWidth: 760 }} onClick={(e) => e.stopPropagation()}><div className="modal-header"><div><h2 style={{ margin: 0 }}>Allocate Remaining Balance</h2><div className="text-muted">Available: {money(payment.unallocated_amount)}</div></div></div><div className="modal-body"><table className="data-table"><thead><tr><th>Bill</th><th style={{ textAlign: 'right' }}>Outstanding</th><th>Allocate</th></tr></thead><tbody>{bills.filter((bill) => !usedBillIds.has(bill.id)).map((bill) => <tr key={bill.id}><td>{bill.bill_number}</td><td style={{ textAlign: 'right' }}>{money(bill.outstanding_amount)}</td><td><input className="input" type="number" min="0" step="0.01" value={allocations[bill.id] || ''} onChange={(e) => setAllocations({ ...allocations, [bill.id]: e.target.value })}/></td></tr>)}</tbody></table></div><div className="modal-footer"><button className="btn btn-secondary" onClick={() => setShowAllocate(false)}>Cancel</button><button className="btn btn-primary" onClick={allocate}>Allocate</button></div></div></div>}
  </div>;
};
