# Generated by Django 5.2.17 on 2026-09-15 04:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_paymentaccountmovement_source_id_and_more'),
        ('inventory', '0007_itemstockadjustment_itemstockbalanceprojection_and_more'),
        ('organizations', '0019_seed_supplier_payment_permissions'),
        ('purchases', '0006_productpurchasetaxmapping_item_and_more'),
        ('shifts', '0012_fuelcreditslip_is_credit_limit_overridden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name_snapshot', models.CharField(max_length=255)),
                ('customer_code_snapshot', models.CharField(blank=True, max_length=50)),
                ('customer_gstin_snapshot', models.CharField(blank=True, max_length=15)),
                ('billing_address_snapshot', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(db_index=True)),
                ('invoice_type', models.CharField(choices=[('credit', 'Credit Invoice'), ('cash', 'Cash Invoice')], max_length=20)),
                ('place_of_supply_state_code', models.CharField(blank=True, max_length=2)),
                ('is_interstate', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('taxable_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='shifts.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organizations.outlet')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sales_invoices', to='finance.paymentaccount')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_audit_events', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='sales.salesinvoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceCreditSlipLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_slip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='shifts.fuelcreditslip')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_slip_links', to='sales.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('item', 'Item'), ('credit_slip', 'Fuel Credit Slip')], max_length=20)),
                ('item_code_snapshot', models.CharField(max_length=50)),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('item_type_snapshot', models.CharField(max_length=30)),
                ('hsn_sac_snapshot', models.CharField(blank=True, max_length=20)),
                ('unit_snapshot', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('tax_treatment_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('tax_regime_snapshot', models.CharField(blank=True, max_length=30)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_components_snapshot', models.JSONField(blank=True, default=list)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='shifts.fuelcreditslip')),
                ('effective_rate_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='purchases.purchasetaxcoderate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='inventory.item')),
                ('tax_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='purchases.purchasetaxcode')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('outlet', 'invoice_number'), name='unique_outlet_sales_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('organisation', 'outlet', 'client_request_id'), name='unique_sales_invoice_client_request'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='sales_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicecreditsliplink',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('credit_slip',), name='unique_active_invoice_credit_slip'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'sequence'), name='unique_sales_invoice_line_sequence'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_invoice_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicesequence',
            constraint=models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_sales_invoice_seq_year'),
        ),
    ]
