# Generated by Django 5.2.17 on 2026-09-15 04:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_paymentaccountmovement_movement_type'),
        ('organizations', '0020_seed_sales_and_item_stock_permissions'),
        ('sales', '0001_initial'),
        ('shifts', '0012_fuelcreditslip_is_credit_limit_overridden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name_snapshot', models.CharField(max_length=255)),
                ('customer_code_snapshot', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=100)),
                ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='shifts.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipts', to='organizations.organisation')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipts', to='organizations.outlet')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipts', to='finance.paymentaccount')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_customer_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReceiptAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.customerreceipt')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='sales.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipt_sequences', to='organizations.outlet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.UniqueConstraint(fields=('outlet', 'receipt_number'), name='unique_outlet_customer_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('organisation', 'outlet', 'client_request_id'), name='unique_customer_receipt_request'),
        ),
        migrations.AddConstraint(
            model_name='customerreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='customer_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerreceiptallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'sales_invoice'), name='unique_customer_receipt_invoice_allocation'),
        ),
        migrations.AddConstraint(
            model_name='customerreceiptsequence',
            constraint=models.UniqueConstraint(fields=('outlet', 'year'), name='unique_outlet_customer_receipt_seq'),
        ),
    ]
