# Generated by Django 5.2.17 on 2026-08-20 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='trial', max_length=20)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_type', models.CharField(choices=[('owner', 'Owner'), ('administrator', 'Administrator'), ('member', 'Member')], max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='organizations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='OutletAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_accesses', to='organizations.organisationmembership')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_accesses', to='organizations.outlet')),
            ],
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['user', 'organisation'], name='organizatio_user_id_cc9665_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['status'], name='organizatio_status_3a900f_idx'),
        ),
        migrations.AddIndex(
            model_name='organisationmembership',
            index=models.Index(fields=['membership_type'], name='organizatio_members_c5e278_idx'),
        ),
        migrations.AddConstraint(
            model_name='organisationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_user_organisation_membership'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['organisation', 'code'], name='organizatio_organis_6b90b4_idx'),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['status'], name='organizatio_status_d4d581_idx'),
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='unique_organisation_outlet_code'),
        ),
        migrations.AddIndex(
            model_name='outletaccess',
            index=models.Index(fields=['membership', 'outlet'], name='organizatio_members_aff443_idx'),
        ),
        migrations.AddConstraint(
            model_name='outletaccess',
            constraint=models.UniqueConstraint(fields=('membership', 'outlet'), name='unique_membership_outlet_access'),
        ),
    ]
