# Generated by Django 5.2.17 on 2026-08-23 12:17

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organisation_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivationOutletAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_outlet_accesses', to='organizations.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationUserActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('membership_type', models.CharField(choices=[('administrator', 'Administrator'), ('member', 'Member')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('activated', 'Activated'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_activations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activations', to='organizations.organisation')),
                ('outlets', models.ManyToManyField(related_name='activations', through='organizations.ActivationOutletAccess', to='organizations.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_roles', to='organizations.organisationuseractivation')),
            ],
        ),
        migrations.AddField(
            model_name='activationoutletaccess',
            name='activation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_outlet_accesses', to='organizations.organisationuseractivation'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='organisationuseractivation',
            name='roles',
            field=models.ManyToManyField(related_name='activations', through='organizations.ActivationRole', to='organizations.role'),
        ),
        migrations.CreateModel(
            name='MembershipRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='organizations.organisationmembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_roles', to='organizations.role')),
            ],
        ),
        migrations.AddField(
            model_name='activationrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_roles', to='organizations.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.permissiondefinition')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organizations.role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='organizations.RolePermission', to='organizations.permissiondefinition'),
        ),
        migrations.AddConstraint(
            model_name='activationoutletaccess',
            constraint=models.UniqueConstraint(fields=('activation', 'outlet'), name='unique_activation_outlet_access'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_membership_role'),
        ),
        migrations.AddConstraint(
            model_name='activationrole',
            constraint=models.UniqueConstraint(fields=('activation', 'role'), name='unique_activation_role'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organisation'), name='unique_organisation_role_name_case_insensitive'),
        ),
    ]
