# Generated by Django 5.2.17 on 2026-08-23 12:18

from django.db import migrations

def seed_permissions_and_default_roles(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        # Organisation
        {"code": "organisation.view", "name": "View Organisation", "module": "Organisation", "description": "Can view organization profile details."},
        {"code": "organisation.update", "name": "Update Organisation", "module": "Organisation", "description": "Can update organization profile details."},
        # Outlets
        {"code": "outlet.view", "name": "View Outlets", "module": "Outlets", "description": "Can view outlets list and details."},
        {"code": "outlet.create", "name": "Create Outlets", "module": "Outlets", "description": "Can create new outlets."},
        {"code": "outlet.update", "name": "Update Outlets", "module": "Outlets", "description": "Can update outlet details."},
        {"code": "outlet.deactivate", "name": "Deactivate Outlets", "module": "Outlets", "description": "Can deactivate outlets."},
        # Financial Years
        {"code": "financial_year.view", "name": "View Financial Years", "module": "Financial Years", "description": "Can view financial years."},
        {"code": "financial_year.update", "name": "Update Financial Years", "module": "Financial Years", "description": "Can update/close financial years."},
        # Users
        {"code": "user.view", "name": "View Users", "module": "Users", "description": "Can view memberships and activations."},
        {"code": "user.add", "name": "Add Users", "module": "Users", "description": "Can add new users and manage activations."},
        {"code": "user.update", "name": "Update Users", "module": "Users", "description": "Can update user roles and outlet access."},
        {"code": "user.suspend", "name": "Suspend Users", "module": "Users", "description": "Can suspend or reactivate memberships."},
        # Roles
        {"code": "role.view", "name": "View Roles", "module": "Roles", "description": "Can view system and custom roles."},
        {"code": "role.create", "name": "Create Roles", "module": "Roles", "description": "Can create custom roles."},
        {"code": "role.update", "name": "Update Roles", "module": "Roles", "description": "Can update custom roles and permission mappings."},
        {"code": "role.delete", "name": "Delete Roles", "module": "Roles", "description": "Can delete custom roles."},
        # Settings
        {"code": "settings.view", "name": "View Settings", "module": "Settings", "description": "Can view application settings."},
        {"code": "settings.update", "name": "Update Settings", "module": "Settings", "description": "Can update application settings."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    # Now create default roles for all existing organizations
    # Mappings
    default_roles = [
        {
            'name': 'Administrator',
            'description': 'Full access to all foundation features.',
            'permissions': [
                'organisation.view', 'organisation.update',
                'outlet.view', 'outlet.create', 'outlet.update', 'outlet.deactivate',
                'financial_year.view', 'financial_year.update',
                'user.view', 'user.add', 'user.update', 'user.suspend',
                'role.view', 'role.create', 'role.update', 'role.delete',
                'settings.view', 'settings.update'
            ]
        },
        {
            'name': 'Manager',
            'description': 'Manage daily operations, users, and settings.',
            'permissions': [
                'organisation.view',
                'outlet.view', 'outlet.create', 'outlet.update',
                'financial_year.view',
                'user.view',
                'role.view',
                'settings.view'
            ]
        },
        {
            'name': 'Accountant',
            'description': 'Financial access and settings view.',
            'permissions': [
                'organisation.view',
                'outlet.view',
                'financial_year.view',
                'settings.view'
            ]
        },
        {
            'name': 'Shift Operator',
            'description': 'Operational view access.',
            'permissions': [
                'organisation.view',
                'outlet.view'
            ]
        },
        {
            'name': 'Viewer',
            'description': 'Read-only access to foundation features.',
            'permissions': [
                'organisation.view',
                'outlet.view',
                'financial_year.view'
            ]
        }
    ]

    for org in Organisation.objects.all():
        for dr in default_roles:
            role, created = Role.objects.get_or_create(
                organisation=org,
                name=dr['name'],
                defaults={
                    'description': dr['description'],
                    'is_system': True,
                    'is_active': True
                }
            )
            # Sync permissions
            active_perms = PermissionDefinition.objects.filter(code__in=dr['permissions'], is_active=True)
            for perm in active_perms:
                RolePermission.objects.get_or_create(role=role, permission=perm)

def rollback_permissions_and_roles(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Role = apps.get_model('organizations', 'Role')
    
    # Delete permissions seeded
    PermissionDefinition.objects.all().delete()
    # Delete default system roles
    Role.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_permissiondefinition_activationoutletaccess_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_permissions_and_default_roles, rollback_permissions_and_roles),
    ]

