# Generated by Django 5.2.17 on 2026-08-24 17:00

from django.db import migrations

def seed_forecourt_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        # Fuel Products
        {"code": "fuel_product.view", "name": "View Fuel Products", "module": "Products", "description": "Can view fuel products list and details."},
        {"code": "fuel_product.create", "name": "Create Fuel Products", "module": "Products", "description": "Can create new fuel products."},
        {"code": "fuel_product.update", "name": "Update Fuel Products", "module": "Products", "description": "Can update fuel product details."},
        {"code": "fuel_product.deactivate", "name": "Deactivate Fuel Products", "module": "Products", "description": "Can deactivate/activate fuel products."},

        # Product Prices
        {"code": "product_price.view", "name": "View Product Prices", "module": "Prices", "description": "Can view product prices list and history."},
        {"code": "product_price.update", "name": "Update Product Prices", "module": "Prices", "description": "Can set new product prices."},

        # Tanks
        {"code": "tank.view", "name": "View Tanks", "module": "Tanks", "description": "Can view tanks list and details."},
        {"code": "tank.create", "name": "Create Tanks", "module": "Tanks", "description": "Can create new storage tanks."},
        {"code": "tank.update", "name": "Update Tanks", "module": "Tanks", "description": "Can update tank details and product assignments."},
        {"code": "tank.deactivate", "name": "Deactivate Tanks", "module": "Tanks", "description": "Can change tank status (active, inactive, maintenance)."},

        # Dispensers
        {"code": "dispenser.view", "name": "View Dispensers", "module": "Dispensers", "description": "Can view dispensers list and details."},
        {"code": "dispenser.create", "name": "Create Dispensers", "module": "Dispensers", "description": "Can create new dispensers."},
        {"code": "dispenser.update", "name": "Update Dispensers", "module": "Dispensers", "description": "Can update dispenser details."},
        {"code": "dispenser.deactivate", "name": "Deactivate Dispensers", "module": "Dispensers", "description": "Can change dispenser status (active, inactive, maintenance)."},

        # Nozzles
        {"code": "nozzle.view", "name": "View Nozzles", "module": "Nozzles", "description": "Can view nozzles list and details."},
        {"code": "nozzle.create", "name": "Create Nozzles", "module": "Nozzles", "description": "Can create new nozzles."},
        {"code": "nozzle.update", "name": "Update Nozzles", "module": "Nozzles", "description": "Can update nozzle details and connected tanks."},
        {"code": "nozzle.deactivate", "name": "Deactivate Nozzles", "module": "Nozzles", "description": "Can change nozzle status (active, inactive, maintenance)."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    # System role definition updates
    role_permission_mappings = {
        'Administrator': [
            'fuel_product.view', 'fuel_product.create', 'fuel_product.update', 'fuel_product.deactivate',
            'product_price.view', 'product_price.update',
            'tank.view', 'tank.create', 'tank.update', 'tank.deactivate',
            'dispenser.view', 'dispenser.create', 'dispenser.update', 'dispenser.deactivate',
            'nozzle.view', 'nozzle.create', 'nozzle.update', 'nozzle.deactivate',
        ],
        'Manager': [
            'fuel_product.view', 'fuel_product.create', 'fuel_product.update',
            'product_price.view', 'product_price.update',
            'tank.view', 'tank.create', 'tank.update',
            'dispenser.view', 'dispenser.create', 'dispenser.update',
            'nozzle.view', 'nozzle.create', 'nozzle.update',
        ],
        'Accountant': [
            'fuel_product.view',
            'product_price.view', 'product_price.update',
            'tank.view',
            'dispenser.view',
            'nozzle.view',
        ],
        'Shift Operator': [
            'fuel_product.view',
            'product_price.view',
            'tank.view',
            'dispenser.view',
            'nozzle.view',
        ],
        'Viewer': [
            'fuel_product.view',
            'product_price.view',
            'tank.view',
            'dispenser.view',
            'nozzle.view',
        ]
    }

    # Apply to existing roles
    for org in Organisation.objects.all():
        for role_name, perm_codes in role_permission_mappings.items():
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                active_perms = PermissionDefinition.objects.filter(code__in=perm_codes, is_active=True)
                for perm in active_perms:
                    RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass

def rollback_forecourt_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    forecourt_perm_codes = [
        'fuel_product.view', 'fuel_product.create', 'fuel_product.update', 'fuel_product.deactivate',
        'product_price.view', 'product_price.update',
        'tank.view', 'tank.create', 'tank.update', 'tank.deactivate',
        'dispenser.view', 'dispenser.create', 'dispenser.update', 'dispenser.deactivate',
        'nozzle.view', 'nozzle.create', 'nozzle.update', 'nozzle.deactivate',
    ]

    # Delete RolePermission mappings first
    RolePermission.objects.filter(permission__code__in=forecourt_perm_codes).delete()
    # Delete the definitions
    PermissionDefinition.objects.filter(code__in=forecourt_perm_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_seed_permissions_and_default_roles'),
    ]

    operations = [
        migrations.RunPython(seed_forecourt_permissions, rollback_forecourt_permissions),
    ]
