# Generated by Django 5.2.17 on 2026-08-26 12:00

from django.db import migrations

def seed_milestone8_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        # Employees
        {"code": "employee.view", "name": "View Employees", "module": "Employees", "description": "Can view employee list and details."},
        {"code": "employee.create", "name": "Create Employees", "module": "Employees", "description": "Can create new employees."},
        {"code": "employee.update", "name": "Update Employees", "module": "Employees", "description": "Can update employee details."},
        {"code": "employee.deactivate", "name": "Deactivate Employees", "module": "Employees", "description": "Can deactivate/reactivate employees."},

        # Designations
        {"code": "employee_designation.view", "name": "View Designations", "module": "Employees", "description": "Can view designations."},
        {"code": "employee_designation.create", "name": "Create Designations", "module": "Employees", "description": "Can create designations."},
        {"code": "employee_designation.update", "name": "Update Designations", "module": "Employees", "description": "Can update designations."},
        {"code": "employee_designation.deactivate", "name": "Deactivate Designations", "module": "Employees", "description": "Can deactivate designations."},

        # Shift setup
        {"code": "shift_definition.view", "name": "View Shift Definitions", "module": "Shifts", "description": "Can view shift definitions."},
        {"code": "shift_definition.create", "name": "Create Shift Definitions", "module": "Shifts", "description": "Can create shift definitions."},
        {"code": "shift_definition.update", "name": "Update Shift Definitions", "module": "Shifts", "description": "Can update shift definitions."},
        {"code": "shift_definition.deactivate", "name": "Deactivate Shift Definitions", "module": "Shifts", "description": "Can deactivate shift definitions."},

        # Roster
        {"code": "shift_roster.view", "name": "View Shift Rosters", "module": "Shifts", "description": "Can view shift rosters."},
        {"code": "shift_roster.create", "name": "Create Shift Rosters", "module": "Shifts", "description": "Can create shift rosters."},
        {"code": "shift_roster.update", "name": "Update Shift Rosters", "module": "Shifts", "description": "Can update shift rosters."},

        # Opening balances
        {"code": "opening_balance.view", "name": "View Opening Balances", "module": "Balances", "description": "Can view opening balances."},
        {"code": "opening_balance.configure", "name": "Configure Opening Balances", "module": "Balances", "description": "Can configure opening balances."},
        {"code": "opening_balance.confirm", "name": "Confirm Opening Balances", "module": "Balances", "description": "Can confirm opening balances."},

        # Calibration
        {"code": "dip_calibration.view", "name": "View Calibrations", "module": "Calibrations", "description": "Can view calibration charts and tank assignments."},
        {"code": "dip_calibration.import", "name": "Import Calibrations", "module": "Calibrations", "description": "Can import calibration charts."},
        {"code": "dip_calibration.update", "name": "Update Calibrations", "module": "Calibrations", "description": "Can update calibration details."},
        {"code": "dip_calibration.activate", "name": "Activate Calibrations", "module": "Calibrations", "description": "Can activate calibration charts."},
        {"code": "dip_calibration.assign", "name": "Assign Calibrations", "module": "Calibrations", "description": "Can assign calibration charts to tanks."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    # System role definition updates
    role_permission_mappings = {
        'Administrator': [
            'employee.view', 'employee.create', 'employee.update', 'employee.deactivate',
            'employee_designation.view', 'employee_designation.create', 'employee_designation.update', 'employee_designation.deactivate',
            'shift_definition.view', 'shift_definition.create', 'shift_definition.update', 'shift_definition.deactivate',
            'shift_roster.view', 'shift_roster.create', 'shift_roster.update',
            'opening_balance.view', 'opening_balance.configure', 'opening_balance.confirm',
            'dip_calibration.view', 'dip_calibration.import', 'dip_calibration.update', 'dip_calibration.activate', 'dip_calibration.assign',
        ],
        'Manager': [
            'employee.view', 'employee.create', 'employee.update',
            'employee_designation.view', 'employee_designation.create', 'employee_designation.update',
            'shift_definition.view', 'shift_definition.create', 'shift_definition.update',
            'shift_roster.view', 'shift_roster.create', 'shift_roster.update',
            'opening_balance.view', 'opening_balance.configure', 'opening_balance.confirm',
            'dip_calibration.view', 'dip_calibration.import', 'dip_calibration.update', 'dip_calibration.activate', 'dip_calibration.assign',
        ],
        'Accountant': [
            'employee.view',
            'shift_definition.view',
            'shift_roster.view',
            'opening_balance.view', 'opening_balance.confirm',
            'dip_calibration.view',
        ],
        'Shift Operator': [
            'employee.view',
            'shift_definition.view',
            'shift_roster.view',
            'dip_calibration.view',
            'opening_balance.view',
        ],
        'Viewer': [
            'employee.view',
            'employee_designation.view',
            'shift_definition.view',
            'shift_roster.view',
            'opening_balance.view',
            'dip_calibration.view',
        ]
    }

    # Apply to existing roles
    for org in Organisation.objects.all():
        for role_name, perm_codes in role_permission_mappings.items():
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                active_perms = PermissionDefinition.objects.filter(code__in=perm_codes, is_active=True)
                for perm in active_perms:
                    RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass

def rollback_milestone8_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    m8_perm_codes = [
        'employee.view', 'employee.create', 'employee.update', 'employee.deactivate',
        'employee_designation.view', 'employee_designation.create', 'employee_designation.update', 'employee_designation.deactivate',
        'shift_definition.view', 'shift_definition.create', 'shift_definition.update', 'shift_definition.deactivate',
        'shift_roster.view', 'shift_roster.create', 'shift_roster.update',
        'opening_balance.view', 'opening_balance.configure', 'opening_balance.confirm',
        'dip_calibration.view', 'dip_calibration.import', 'dip_calibration.update', 'dip_calibration.activate', 'dip_calibration.assign',
    ]

    # Delete RolePermission mappings first
    RolePermission.objects.filter(permission__code__in=m8_perm_codes).delete()
    # Delete the definitions
    PermissionDefinition.objects.filter(code__in=m8_perm_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_seed_forecourt_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_milestone8_permissions, rollback_milestone8_permissions),
    ]
