# Generated by Django 5.2.17 on 2026-09-02 11:00

from django.db import migrations

def seed_milestone9_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        # Operational Shifts
        {"code": "shift.view", "name": "View Shifts", "module": "Shifts", "description": "Can view operational shifts, meter readings, testing, dips and summaries."},
        {"code": "shift.open", "name": "Open Shifts", "module": "Shifts", "description": "Can open live operational shifts."},
        {"code": "shift.update_open", "name": "Update Open Shifts", "module": "Shifts", "description": "Can update assignments and live operations on an open shift."},
        {"code": "shift.close", "name": "Close Shifts", "module": "Shifts", "description": "Can close operational shifts."},
        {"code": "shift.reopen", "name": "Reopen Shifts", "module": "Shifts", "description": "Can reopen closed operational shifts with mandatory reason."},

        # Meter Readings & Events
        {"code": "meter_reading.view", "name": "View Meter Readings", "module": "Meters", "description": "Can view meter readings and price segments."},
        {"code": "meter_reading.record", "name": "Record Meter Readings", "module": "Meters", "description": "Can record closing meter readings on live open shifts."},
        {"code": "meter_reading.correct", "name": "Correct Meter Readings", "module": "Meters", "description": "Can correct meter readings or provide manual opening exceptions."},
        {"code": "meter_event.record", "name": "Record Meter Events", "module": "Meters", "description": "Can record meter replacement, reset, rollover, or correction events."},

        # Testing Records
        {"code": "testing.view", "name": "View Testing Records", "module": "Testing", "description": "Can view shift testing records."},
        {"code": "testing.record", "name": "Record Testing", "module": "Testing", "description": "Can record testing quantity on an open shift."},
        {"code": "testing.update", "name": "Update Testing", "module": "Testing", "description": "Can update testing records on an open shift."},
        {"code": "testing.delete", "name": "Delete Testing", "module": "Testing", "description": "Can delete testing records on an open shift."},

        # Dip Observations
        {"code": "dip_reading.view", "name": "View Dip Readings", "module": "Dips", "description": "Can view tank dip observations."},
        {"code": "dip_reading.record", "name": "Record Dip Readings", "module": "Dips", "description": "Can record tank dip observations on an open shift."},
        {"code": "dip_reading.correct", "name": "Correct Dip Readings", "module": "Dips", "description": "Can correct or manually enter tank dip observations with mandatory reason."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    # System role definition updates
    role_permission_mappings = {
        'Administrator': [
            'shift.view', 'shift.open', 'shift.update_open', 'shift.close', 'shift.reopen',
            'meter_reading.view', 'meter_reading.record', 'meter_reading.correct', 'meter_event.record',
            'testing.view', 'testing.record', 'testing.update', 'testing.delete',
            'dip_reading.view', 'dip_reading.record', 'dip_reading.correct',
        ],
        'Manager': [
            'shift.view', 'shift.open', 'shift.update_open', 'shift.close',
            'meter_reading.view', 'meter_reading.record', 'meter_reading.correct', 'meter_event.record',
            'testing.view', 'testing.record', 'testing.update', 'testing.delete',
            'dip_reading.view', 'dip_reading.record', 'dip_reading.correct',
        ],
        'Accountant': [
            'shift.view',
            'meter_reading.view',
            'testing.view',
            'dip_reading.view',
        ],
        'Shift Operator': [
            'shift.view', 'shift.open', 'shift.update_open',
            'meter_reading.view', 'meter_reading.record',
            'testing.view', 'testing.record',
            'dip_reading.view', 'dip_reading.record',
        ],
        'Viewer': [
            'shift.view',
            'meter_reading.view',
            'testing.view',
            'dip_reading.view',
        ]
    }

    # Apply to existing system roles
    for org in Organisation.objects.all():
        for role_name, perm_codes in role_permission_mappings.items():
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                active_perms = PermissionDefinition.objects.filter(code__in=perm_codes, is_active=True)
                for perm in active_perms:
                    RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass


def rollback_milestone9_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    m9_perm_codes = [
        'shift.view', 'shift.open', 'shift.update_open', 'shift.close', 'shift.reopen',
        'meter_reading.view', 'meter_reading.record', 'meter_reading.correct', 'meter_event.record',
        'testing.view', 'testing.record', 'testing.update', 'testing.delete',
        'dip_reading.view', 'dip_reading.record', 'dip_reading.correct',
    ]

    # Delete RolePermission mappings first
    RolePermission.objects.filter(permission__code__in=m9_perm_codes).delete()
    # Delete the definitions
    PermissionDefinition.objects.filter(code__in=m9_perm_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_seed_milestone8_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_milestone9_permissions, rollback_milestone9_permissions),
    ]
