# Generated by Django on 2026-09-02

from django.db import migrations

def seed_handover_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        {
            "code": "shift.nozzle_handover",
            "name": "Handover Shift Nozzle",
            "module": "Shifts",
            "description": "Can perform mid-shift nozzle attendant handovers with verified meter totalizers."
        },
        {
            "code": "shift.cashier_transfer",
            "name": "Transfer Primary Cashier",
            "module": "Shifts",
            "description": "Can transfer primary cashier accountability with audit period tracking."
        },
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    # Assign to Administrator and Manager system roles across organisations
    role_names = ['Administrator', 'Manager']
    new_perm_codes = ['shift.nozzle_handover', 'shift.cashier_transfer']

    for org in Organisation.objects.all():
        for role_name in role_names:
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                active_perms = PermissionDefinition.objects.filter(code__in=new_perm_codes, is_active=True)
                for perm in active_perms:
                    RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass


def rollback_handover_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    perm_codes = ['shift.nozzle_handover', 'shift.cashier_transfer']
    RolePermission.objects.filter(permission__code__in=perm_codes).delete()
    PermissionDefinition.objects.filter(code__in=perm_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_seed_milestone9_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_handover_permissions, rollback_handover_permissions),
    ]
