# Generated by Django on 2026-09-04

from django.db import migrations

def seed_nozzle_commission_permission(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # 1. Seed PermissionDefinition
    perm, _ = PermissionDefinition.objects.update_or_create(
        code='nozzle.commission',
        defaults={
            'name': 'Commission Nozzles',
            'module': 'Forecourt',
            'description': 'Can commission new nozzles and establish their initial authoritative starting totalizer.',
            'is_active': True,
        }
    )

    # 2. Assign to Administrator and Manager system roles across organisations
    role_names = ['Administrator', 'Manager']

    for org in Organisation.objects.all():
        for role_name in role_names:
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass


def rollback_nozzle_commission_permission(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    perm_code = 'nozzle.commission'
    RolePermission.objects.filter(permission__code=perm_code).delete()
    PermissionDefinition.objects.filter(code=perm_code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_seed_handover_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_nozzle_commission_permission, rollback_nozzle_commission_permission),
    ]
