# Generated by Django forward migration for removing shift.cashier_transfer permission

from django.db import migrations


def remove_cashier_transfer_permission(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    perm_code = 'shift.cashier_transfer'
    RolePermission.objects.filter(permission__code=perm_code).delete()
    PermissionDefinition.objects.filter(code=perm_code).delete()


def rollback_remove_cashier_transfer_permission(apps, schema_editor):
    # Backward migration: no-op since primary cashier workflow is deprecated
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_seed_nozzle_commission_permission'),
    ]

    operations = [
        migrations.RunPython(
            remove_cashier_transfer_permission,
            rollback_remove_cashier_transfer_permission
        ),
    ]
