# Generated by Django on 2026-09-04

from django.db import migrations

def seed_milestone10_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    # Seed Permissions
    permissions_to_seed = [
        # Customers
        {"code": "customer.view", "name": "View Customers", "module": "Customers", "description": "Can view customers and credit positions."},
        {"code": "customer.create", "name": "Create Customers", "module": "Customers", "description": "Can create new customers."},
        {"code": "customer.update", "name": "Update Customers", "module": "Customers", "description": "Can update customer details."},
        {"code": "customer.deactivate", "name": "Deactivate Customers", "module": "Customers", "description": "Can deactivate customers."},

        # Credit Slips
        {"code": "credit_slip.view", "name": "View Credit Slips", "module": "Sales", "description": "Can view fuel credit slips."},
        {"code": "credit_slip.create", "name": "Create Credit Slips", "module": "Sales", "description": "Can create customer fuel credit slips."},
        {"code": "credit_slip.update", "name": "Update Credit Slips", "module": "Sales", "description": "Can update un-reconciled credit slips."},
        {"code": "credit_slip.void", "name": "Void Credit Slips", "module": "Sales", "description": "Can void fuel credit slips with reason."},

        # Collections
        {"code": "collection.view", "name": "View Shift Collections", "module": "Collections", "description": "Can view employee collections."},
        {"code": "collection.create", "name": "Create Shift Collections", "module": "Collections", "description": "Can record employee cash, card, or UPI collections."},
        {"code": "collection.update", "name": "Update Shift Collections", "module": "Collections", "description": "Can update un-reconciled employee collections."},
        {"code": "collection.void", "name": "Void Shift Collections", "module": "Collections", "description": "Can void employee collections with reason."},

        # Shift deductions & adjustments
        {"code": "shift_deduction.view", "name": "View Shift Deductions", "module": "Collections", "description": "Can view shift deductions and adjustments."},
        {"code": "shift_deduction.create", "name": "Create Shift Deductions", "module": "Collections", "description": "Can record shift deductions and adjustments."},
        {"code": "shift_deduction.approve", "name": "Approve Shift Deductions", "module": "Collections", "description": "Can approve shift deductions and expense adjustments."},
        {"code": "shift_deduction.void", "name": "Void Shift Deductions", "module": "Collections", "description": "Can void shift deductions with reason."},

        # Reconciliation
        {"code": "reconciliation.view", "name": "View Reconciliation", "module": "Reconciliation", "description": "Can view employee and shift reconciliations."},
        {"code": "reconciliation.reconcile", "name": "Reconcile Settlements", "module": "Reconciliation", "description": "Can confirm and reconcile employee shift settlements."},
        {"code": "reconciliation.reopen", "name": "Reopen Settlements", "module": "Reconciliation", "description": "Can reopen reconciled settlements with reason."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    all_m10_codes = [p['code'] for p in permissions_to_seed]

    role_permission_mappings = {
        'Administrator': all_m10_codes,
        'Manager': all_m10_codes,
        'Accountant': [
            'customer.view', 'customer.create', 'customer.update',
            'credit_slip.view',
            'collection.view',
            'shift_deduction.view',
            'reconciliation.view', 'reconciliation.reconcile'
        ],
        'Shift Operator': [
            'customer.view',
            'credit_slip.view', 'credit_slip.create', 'credit_slip.update',
            'collection.view', 'collection.create', 'collection.update',
            'reconciliation.view'
        ],
        'Viewer': [
            'customer.view',
            'credit_slip.view',
            'collection.view',
            'shift_deduction.view',
            'reconciliation.view'
        ]
    }

    # Apply to existing system roles across all organisations
    for org in Organisation.objects.all():
        for role_name, perm_codes in role_permission_mappings.items():
            try:
                role = Role.objects.get(organisation=org, name=role_name, is_system=True)
                active_perms = PermissionDefinition.objects.filter(code__in=perm_codes, is_active=True)
                for perm in active_perms:
                    RolePermission.objects.get_or_create(role=role, permission=perm)
            except Role.DoesNotExist:
                pass


def rollback_milestone10_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    m10_perm_codes = [
        'customer.view', 'customer.create', 'customer.update', 'customer.deactivate',
        'credit_slip.view', 'credit_slip.create', 'credit_slip.update', 'credit_slip.void',
        'collection.view', 'collection.create', 'collection.update', 'collection.void',
        'shift_deduction.view', 'shift_deduction.create', 'shift_deduction.approve', 'shift_deduction.void',
        'reconciliation.view', 'reconciliation.reconcile', 'reconciliation.reopen'
    ]

    RolePermission.objects.filter(permission__code__in=m10_perm_codes).delete()
    PermissionDefinition.objects.filter(code__in=m10_perm_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_cashier_transfer_permission'),
    ]

    operations = [
        migrations.RunPython(seed_milestone10_permissions, rollback_milestone10_permissions),
    ]
