# Generated by Django on 2026-09-07

from django.db import migrations

def seed_shift_card_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    Organisation = apps.get_model('organizations', 'Organisation')
    Role = apps.get_model('organizations', 'Role')
    RolePermission = apps.get_model('organizations', 'RolePermission')

    permissions_to_seed = [
        {"code": "shift.void", "name": "Void Shift Cards", "module": "Operations", "description": "Can void employee shift cards with mandatory reason."},
        {"code": "shift.lock", "name": "Lock Shift Records", "module": "Operations", "description": "Can manually lock shift cards and parent shifts."},
        {"code": "shift.unlock", "name": "Unlock Shift Records", "module": "Operations", "description": "Can unlock locked shift cards with reason."},
    ]

    for p_data in permissions_to_seed:
        PermissionDefinition.objects.update_or_create(
            code=p_data['code'],
            defaults={
                'name': p_data['name'],
                'module': p_data['module'],
                'description': p_data['description'],
                'is_active': True
            }
        )

    admin_perms = ['shift.void', 'shift.lock', 'shift.unlock']
    manager_perms = ['shift.void', 'shift.lock']

    for org in Organisation.objects.all():
        try:
            admin_role = Role.objects.get(organisation=org, name='Administrator', is_system=True)
            for perm in PermissionDefinition.objects.filter(code__in=admin_perms, is_active=True):
                RolePermission.objects.get_or_create(role=admin_role, permission=perm)
        except Role.DoesNotExist:
            pass

        try:
            manager_role = Role.objects.get(organisation=org, name='Manager', is_system=True)
            for perm in PermissionDefinition.objects.filter(code__in=manager_perms, is_active=True):
                RolePermission.objects.get_or_create(role=manager_role, permission=perm)
        except Role.DoesNotExist:
            pass


def rollback_shift_card_permissions(apps, schema_editor):
    PermissionDefinition = apps.get_model('organizations', 'PermissionDefinition')
    codes = ['shift.void', 'shift.lock', 'shift.unlock']
    PermissionDefinition.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_seed_milestone10_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_shift_card_permissions, rollback_shift_card_permissions),
    ]
