# Generated by Django 5.2.17 on 2026-09-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_seed_milestone11_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=100, null=True),
        ),
    ]
