# Generated by Django 5.2.17 on 2026-09-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_seed_milestone12_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
